### ISSUE TITLE
Strange issue with indicator appearing under wrong tab

### ISSUE THREAD

**Issue by alexpchin** [PedroBern/react-native-collapsible-tab-view#100]
I'm still trying to work out exactly the scenario that this happens in, but sometimes the indicator shows underneath the wrong tab. 

![image](https://user-images.githubusercontent.com/40461/107175316-6e4d5380-69c4-11eb-9811-b3ffc7f514ef.jpeg)

**Comment by PedroBern** [comment]
🎉  issue #100 🎉 

@alexpchin this is probably fixed in #93
