### ISSUE TITLE
When `scrollEnabled` indicator does not show

### ISSUE THREAD

**Issue by alexpchin** [PedroBern/react-native-collapsible-tab-view#109]
Continuing with these really strange bugs... when `scrollEnabled` is enabled on Tabs.MaterialTabBar, the indicator isn't showing up.

```
.
.
TabBarComponent={(props) => (
  <Tabs.MaterialTabBar {...props} scrollEnabled />
)}
.
.
```

With scrollEnabled: 
 
<img src="https://user-images.githubusercontent.com/40461/107503099-71496f00-6b91-11eb-8814-10243c1dad24.png" width="200px" />

Without scrollEnabled:

<img src="https://user-images.githubusercontent.com/40461/107503260-a5249480-6b91-11eb-9b7d-e77759fa861d.png" width="200px" />

I have definitely only used Tabs from the package. 
In my custom TabBar, I have a couple of modifications I show icons on some pages instead of words and I have some pages where message badges are added etc.

```
import * as Tabs from 'react-native-collapsible-tab-view';

.
.

const TabBar = ({ activeColor, inactiveColor, tabBarItemProps, ...props }) => (
  <Tabs.MaterialTabBar
    activeColor={activeColor}
    inactiveColor={inactiveColor}
    indicatorStyle={styles.indicatorStyle}
    TabItemComponent={(tabBarProps) => (
      <TabBarItem {...tabBarItemProps} {...tabBarProps} />
    )}
    {...props}
  />
);
```

As a side point, I also add `numberOfLines={1}` to the TabBar Item text just to ensure that it doesn't wrap (just in case).

**Comment by alexpchin** [comment]
@andreialecu I have pushed an example of this to your bare repo `https://github.com/andreialecu/rnctv-react-native-bare-test/pull/1`

**Comment by andreialecu** [comment]
![simulator_screenshot_284E50C1-0DA1-431B-8479-C8F465C7D45B](https://user-images.githubusercontent.com/697707/107514632-98646880-6bb2-11eb-874f-bdb4d68898ca.png)

I checked out your PR and I can see the indicator. What am I missing?

**Comment by alexpchin** [comment]
@andreialecu Sorry for the delay... When I run that PR, I currently see:

<img src="https://user-images.githubusercontent.com/40461/107519702-79f96f80-6ba8-11eb-889f-c30935e0095f.png" width="200px" />

I'm running iPhone 11 iOS 14.4.

**Comment by alexpchin** [comment]
@andreialecu Just FYI after updating to `4.0.0-rc.2` I'm still not seeing the indicator.

**Comment by andreialecu** [comment]
I still can't reproduce it. If you figure it out please open a PR.

**Comment by alexpchin** [comment]
Ok... If I change directly from `lib/module/MaterialTabBar/TabBar.js`:

```
const [itemsLayout, setItemsLayout] = React.useState(scrollEnabled ? [] : tabNames.map((_, i) => {
    const tabWidth = windowWidth / nTabs;
    return {
      width: tabWidth,
      x: i * tabWidth
    };
  }));
```

To:

```
const [itemsLayout, setItemsLayout] = React.useState(tabNames.map((_, i) => {
    const tabWidth = windowWidth / nTabs;
    return {
      width: tabWidth,
      x: i * tabWidth
    };
  }));
```

Then I can see the indicator appearing on the far right...

<img src="https://user-images.githubusercontent.com/40461/107579453-13e30b80-6bed-11eb-8506-ca454e028cb5.png" 
 width="400px" />
