### ISSUE TITLE
Content showing below header until move

### ISSUE THREAD

**Issue by alexpchin** [PedroBern/react-native-collapsible-tab-view#113]
On initial load, the content shows below the header. 

![Screenshot 2021-02-10 at 16 13 05](https://user-images.githubusercontent.com/40461/107540410-ec287f00-6bbd-11eb-99e8-c02424a73a54.png)

After scrolling, the content then moves to the correct place. @andreialecu Does this happen on the updated PR for you too? https://github.com/andreialecu/rnctv-react-native-bare-test/pull/1 I am concerned as I'm still not seeing the indicator when `scrollEnabled` is set as per #109

**Comment by andreialecu** [comment]
I can repro this one. Checking.

**Comment by andreialecu** [comment]
@alexpchin can you do me a favor and pull the change I made to the PR and tell me if you can also see this extra space between the tab bar and the albums when scrolling down?

![simulator_screenshot_9D5DA805-AFF5-4327-B30B-12A7EFED4A9C](https://user-images.githubusercontent.com/697707/107546171-be026980-6bd4-11eb-8dd6-506fe5561898.png)

**Comment by alexpchin** [comment]
@andreialecu Yes, I also see that after I have scrolled down.

**Comment by alexpchin** [comment]
Also... I've just noticed, I can see the indicator too.

<img src="https://user-images.githubusercontent.com/40461/107548086-23029300-6bc6-11eb-97fa-5dd45dcf2940.png" width="400px" />

**Comment by andreialecu** [comment]
I found what the problem is, will open a PR shortly. Seems to be a difference between Expo and bare RN.

More specifically it seems that `automaticallyAdjustContentInsets` needs to be set to `false` on the inner scroll view.

This resolves the main issue you're seeing. Will open a PR shortly after testing it further.

**Comment by andreialecu** [comment]
If you manually edit this file in `node_modules`, as per the screenshot below, this should work:

<img width="755" alt="Screenshot 2021-02-10 at 19 43 34" src="https://user-images.githubusercontent.com/697707/107549251-46363e00-6bd8-11eb-94c7-9bd13a93fa22.png">

**Comment by andreialecu** [comment]
Here's a build containing all recent fixes, until rc.1 is released (should be later today):

[react-native-collapsible-tab-view-v4.0.0-rc.1.tgz.zip](https://github.com/PedroBern/react-native-collapsible-tab-view/files/5960276/react-native-collapsible-tab-view-v4.0.0-rc.1.tgz.zip)

**Comment by andreialecu** [comment]
@alexpchin try `4.0.0-rc.2`

**Comment by alexpchin** [comment]
Thanks! @andreialecu
