### ISSUE TITLE
On first load content shifts down (adjust is visible)

### ISSUE THREAD

**Issue by alexpchin** [PedroBern/react-native-collapsible-tab-view#119]
When first loading a page with tabs, the tab content shifts down. This doesn't happen after page load or on refresh. See video.

Running in a bare app, on iOS simulator using version `4.0.0-rc.2`.

[simulator1.mov.zip](https://github.com/PedroBern/react-native-collapsible-tab-view/files/5962342/simulator1.mov.zip)

**Comment by andreialecu** [comment]
#120 may help with this, but not sure.

If you have a repro that would also be great.

**Comment by danielfein** [comment]
I'm also seeing this, now with `rc.3`. It seems to be when navigating from screen to screen where they're both implementing the same components with different content.

There's also a lot of flashing as the component seems to be trying to load the Tab even before the Header, and then it sort of gets confused with what is and isn't on screen. I have this structure:
```
<Tabs.Tab>
<Tabs.FlatList />
</Tabs.Tab>
```
and the FlatList component will load full screen (initially it loads the ListEmpty component), then flash, then load the header, then scroll to the bottom of the FlatList and the Header will be at the minimum header height. I think somewhere along the lines the updated FlatList is being scrolled to the bottom which is throwing it off a bit.

I also tried throwing FlatList inside Lazy to see if it was a load time issue but that didn't have much effect.

**Comment by PedroBern** [comment]
@danielfein a repro would be helpful

**Comment by alexpchin** [comment]
I've made a PR on @andreialecu's bare repo trying show some of the odd behaviour. It's not 100% there as I haven't found out what is causing the initiall movement but you can see some other quirks? 

https://github.com/andreialecu/rnctv-react-native-bare-test/pull/2

It might be relatede to react-navigation?

**Comment by alexpchin** [comment]
@danielfein Are you able to pull my PR with the repro and see if it's the same issue you are facing?

**Comment by alexpchin** [comment]
@PedroBern @andreialecu In order to help further, I have created a PR (not intended to be merged of course) just to check what happens on Expo when you add react-navigation and whether you also get the same issue with the content moving around on the first load. However, it seems like it's not happening the same on expo (not as jittery). 

However, there are some other problems:

- [ ] Only when no snapThreshold is provided, after scrolling down, space remains under the tabs

<img src="https://user-images.githubusercontent.com/40461/107845170-69780d80-6dd1-11eb-8675-eb2a012c3fe9.png" width="400px" />

- [ ] Hard to replicate but sometimes if you navigate away from the page and then return, the content shows below the header.

You can compare this with https://github.com/andreialecu/rnctv-react-native-bare-test/pull/2 

This issue is currently a significant blocker to my project as I am seeing a lot more movement on first load similar to @danielfein I think? I attach another video. I will continue to investigate.

[RPReplay_Final1613204202.mov.zip](https://github.com/PedroBern/react-native-collapsible-tab-view/files/5975333/RPReplay_Final1613204202.mov.zip)

I hope these repros help resolve the problem.

**Comment by andreialecu** [comment]
@alexpchin I'm going to take a look at this. I have an idea why it may happen. The gap seems equal to the header height, so it's a content inset issue.

Please join https://discord.gg/YTN3N8Hq if you'd like to coordinate in more real time on this. It was created for this project, but hasn't been added to the readme yet.

**Comment by alexpchin** [comment]
> - [x] Only when no snapThreshold is provided, after scrolling down, space remains under the tabs

This is resolved by `https://github.com/PedroBern/react-native-collapsible-tab-view/commit/040e5c8b6a997dfc460ebb7ffd2a5c0b72f5d78c`

**Comment by alexpchin** [comment]
`rc.5` fixes this issue.

**Comment by shawarmaz** [comment]
Getting this again 
```
    "react-native-collapsible-tab-view": "^6.2.1",

```
