### ISSUE TITLE
Scroll to top when pressing on a tab should take the tab bar height into account [iOS]

### ISSUE THREAD

**Issue by abelmenkveld** [PedroBern/react-native-collapsible-tab-view#137]
### Current behavior

When you click on a currently open tab for it to scroll to the top, some of the content gets hidden behind the tab bar. This only happens on iOS, on Android the entire header becomes visible. 

### Expected behavior

There should be accounted for the height of the tab bar in the y offset when you press on a tab.

### Screenshots (if applicable)

https://user-images.githubusercontent.com/15447148/108211162-ac691680-712c-11eb-9a4e-83bcb26eb11f.mov

**Comment by alexpchin** [comment]
Hi @abelmenkveld I'm not seeing this happen, are you testing this on Expo and on the example repository?

**Comment by andreialecu** [comment]
Fixed in `rc.10`.
