### ISSUE TITLE
[Typescript] Could not find a declaration file for module 'react-native-collapsible-tab-view'

### ISSUE THREAD

**Issue by sanduluca** [PedroBern/react-native-collapsible-tab-view#139]
I get this Typescript error and have no idea how to solve it. There is not `@types/react-native-collapsible-tab-view`. I see that package is written on Typescript, but I get this error. What is wrong ? How should I solve it ?
```
Could not find a declaration file for module 'react-native-collapsible-tab-view'. 'c:/Projects/my-app/node_modules/react-native-collapsible-tab-view/lib/commonjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-native-collapsible-tab-view` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-collapsible-tab-view';`
```

**Comment by andreialecu** [comment]
Make sure to install `react-native-collapsible-tab-view@next`. The current stable version on npm will be deprecated soon.

**Comment by sanduluca** [comment]
Thank for your quick reply. I updated the package to next version and replace the default example, but now I get this error 
![image](https://user-images.githubusercontent.com/56228534/108389455-5b365100-7218-11eb-8b7b-48bf7fc8d884.png)

**Comment by PedroBern** [comment]
@sanduluca do you get this on v4?

**Comment by sanduluca** [comment]
> @sanduluca do you get this on v4?

Yes.
```json
"dependencies": {
    "...": "...",
    "react-native-collapsible-tab-view": "^4.0.0-rc.11",
    "...": "..."
}
```

**Comment by andreialecu** [comment]
@sanduluca what version on `@types/react-native` do you have installed? 

I had to revert to `"@types/react-native": "^0.62.0",` in a project due to a similar error. I think something is broken in recent typing versions.

**Comment by sanduluca** [comment]
```json
"devDependencies": {
    "@types/react": "^17.0.0"
}
```

**Comment by andreialecu** [comment]
Try changing it to the one I mentioned in the comment above and run an install again, and see if it helps (reload VSCode afterwards to make sure)

**Comment by andreialecu** [comment]
Here's a report of the same kind of issue, from a different library: https://github.com/callstack/react-native-paper/issues/2442

**Comment by sanduluca** [comment]
I've tried patch `0.62.0` and there is no error anymore.
Decided to find out from what patch an error will be raised.
So from patch `0.63.41` (included) there are errors with react-native typings.

**Comment by andreialecu** [comment]
It's been reported in other libraries: 

https://github.com/callstack/react-native-paper/issues/2442

Seems it was broken here:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49983

I'll close this since it's an upstream issue.

**Comment by GermaVinsmoke** [comment]
If you want to use the latest version of `react-native` then can add this comment on top of the `<ScrollView>` component - 
`{/* @ts-ignore */} `

```
{/*// @ts-ignore */}
<Tabs.ScrollView>
  <Text>Second page</Text>
  <Text>Second page</Text>
  <Text>Second page</Text>
</Tabs.ScrollView>
```

**Comment by shyambhongle** [comment]
workaround without ignoring ts
`import {ScrollView} from 'react-native-collapsible-tab-view';`
.....
`
  <ScrollView
      accessibilityComponentType={undefined}
      accessibilityTraits={undefined}>`
.....
`</ScrollView>`
