### ISSUE TITLE
Content jumping as you scroll down 

### ISSUE THREAD

**Issue by alexpchin** [PedroBern/react-native-collapsible-tab-view#145]
### Current behavior

As I'm scrolling down a `Tab.FlatList`, I'm seeing small content adjustments happening. Please see the attached video.

[simulator1.mov.zip](https://github.com/PedroBern/react-native-collapsible-tab-view/files/6037367/simulator1.mov.zip)

This is on a bare react-native app.

### Expected behaviour

The scroll should be smooth.

**Comment by alexpchin** [comment]
I believe the problem goes away if I comment out:

```
onContentSizeChange: scrollContentSizeChangeHandlers
```

In Tab.FlatList.

**Comment by alexpchin** [comment]
The issue is magnified when the list is large... Please see repro here:

https://github.com/andreialecu/rnctv-react-native-bare-test/pull/3

**Comment by andreialecu** [comment]
See #146
