### ISSUE TITLE
TabBar delay when using `lazy` + custom `TabBarComponent`

### ISSUE THREAD

**Issue by alexpchin** [PedroBern/react-native-collapsible-tab-view#147]
### Current behavior

Since 4.0.1, I now see that if you use `lazy` with a custom `TabBarComponent` if you click the tab quickly after the page loads, the wrong TabBarIcon is selected.

If I don't use a custom TabBarComponent then I can't replicate it.

Video with custom `TabComponent`:

[simulator3.mov.zip](https://github.com/PedroBern/react-native-collapsible-tab-view/files/6045569/simulator3.mov.zip)

The same setup without `TabComponent`:

[simulator4.mov.zip](https://github.com/PedroBern/react-native-collapsible-tab-view/files/6045578/simulator4.mov.zip)

(Just FYI - My `TabBarItem` Component is almost exactly the same as the one in the library, except I render an Icon and a notification badge).

```
return (
    <Pressable
      // Removing Android Ripple
      android_ripple={{
        borderless: true,
        color: pressColor,
      }}
      onLayout={onLayout}
      onPress={() => onPress(name)}
      style={({ pressed }) => [
        { opacity: pressed ? pressOpacity : 1 },
        !scrollEnabled ? styles.grow : styles.fixed,
        styles.item,
        style,
      ]}
      {...rest}
    >
      {_hasIcon ? (
        <MaskedView
          maskElement={
            <FontAwesomeIcon color={C.FONT_COLOR} icon={icon} size={22} />
          }
        >
          <Animated.View style={[styles.icon, iconStylez, iconStyle]} />
        </MaskedView>
      ) : (
        <Animated.Text
          numberOfLines={1}
          style={[styles.label, stylez, labelStyle]}
        >
          {label}
        </Animated.Text>
      )}
      {badge > 0 && (
        <View style={styles.badge}>
          <Text
            allowFontScaling={true}
            numberOfLines={1}
            style={styles.badgeTxt}
          >
            {badge}
          </Text>
        </View>
      )}
    </Pressable>
  );
```

**Comment by andreialecu** [comment]
`4.0.1` didn't really change anything that could break this 🤔 

Based on your video it seems that the indicator renders correctly, it's just the highlight that is wrong. That could also be a bug in the custom tab bar though.

Would need a repro in order to investigate.

**Comment by alexpchin** [comment]
Sorry, @andreialecu I wasn't clear when I said that. I just noticed it since installing `4.0.1`. It could have been present before. I will take a deeper dive to see if I can find the cause of the problem.

I think it's unlikely to be my custom tab bar as the logic is almost exactly the same.

**Comment by andreialecu** [comment]
I think #186 should help with this.

**Comment by andreialecu** [comment]
4.2.1 should have some pretty huge performance improvements, which I think should resolve this.

Closing, feel free to ping me to reopen if this is still an issue.
