### ISSUE TITLE
How to trigger an event when header is hidden or trigger an event when scroll down?

### ISSUE THREAD

**Issue by sankar9659** [PedroBern/react-native-collapsible-tab-view#150]
![image](https://user-images.githubusercontent.com/58698022/109503092-d5d85980-7abf-11eb-832c-1fbfcb4b6201.png)
![image](https://user-images.githubusercontent.com/58698022/109503156-e983c000-7abf-11eb-9827-86508fd9d716.png)

How to trigger an event, when scroll down (when the header is hidden).
I m using this package for sticky header.
I want to move the header text in top of the screen. when scroll down (when header is hidden, i need to show the header in top of the screen) like above screenshot.
Here the lorum ipsum shown in header (1st screenshot), when i starts to scroll, i need to show the header in top of the screen) like second image. How can i implement this, any possible?

 "react": "17.0.1",
 "react-native": "0.63.3",
  "react-native-collapsible-tab-view": "^2.0.2",
  
  My code is,
  import React from 'react';
import { StyleSheet, View, Text, Animated } from 'react-native';
import {
    CollapsibleTabView,
    useCollapsibleScene,
} from 'react-native-collapsible-tab-view';

const SomeRoute = ({
    routeKey,
    color,
}) => {
    const scrollPropsAndRef = useCollapsibleScene(routeKey);

    return (
        <Animated.ScrollView
            style={{ backgroundColor: color }}
            {...scrollPropsAndRef}
        >
            <Text style={{ padding: 20, color: "black" }}> Lorem Ipsum is simply</Text>
        </Animated.ScrollView>
    );
};

const renderHeader = () => (
    <View style={styles.header}>
        <Text style={{ padding: 20, color: "white" }}> Lorem Ipsum is Header</Text>
    </View>
);

const renderScene = ({ route, jumpTo }) => {
    switch (route.key) {
        case 'first':
            return <SomeRoute routeKey="first" jumpTo={jumpTo} />;
        case 'second':
            return <SomeRoute routeKey="second" jumpTo={jumpTo} />;
    }
};

const App = () => {
    const [index, setIndex] = React.useState(0);
    const [routes] = React.useState([
        { key: 'first', title: 'First' },
        { key: 'second', title: 'Second' },
    ]);

    const handleIndexChange = (index) => {
        setIndex(index);
    };

    return (
        <View style={{ flex: 1 }}>
            <Text>Sample Text</Text>
            <CollapsibleTabView
                navigationState={{ index, routes }}
                renderScene={renderScene}
                onIndexChange={handleIndexChange}
                renderHeader={renderHeader} // optional
                disableSnap={false}
            />
        </View>
    );
};

export default App;

const styles = StyleSheet.create({
    header: {
        backgroundColor: '#2196f3',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 4,
    },
    headerText: {
        color: 'white',
        fontSize: 24,
    },
    content: {
        height: 1500,
    },
});
  
  Thanks in advance.

**Comment by PedroBern** [comment]
Hi @sankar9659 you can pass an `animatedValue` to the `CollapsibleTabView` and listen to changes on it.

```tsx
const [animatedValue] = React.useState(new Animated.Value(0)

React.useEffect(() => {
    const listener = animatedValue.addListener(({ value }) => {
        ....
    })

    return () => { animatedValue.removerListener(listener) }
}, []}

<CollapsibleTabView
    ...
    animatedValue={animatedValue}
/>
```

**Comment by sankar9659** [comment]
Thanks @PedroBern, But the listener triggers/calls only one time, when i change the tabs the listener not calling. How to fix the issue?

**Comment by abelmenkveld** [comment]
Hi @PedroBern, is there also an approach to accomplish this in v4? The navigation bar I try to animate is located outside of Tabs.Container

**Comment by andreialecu** [comment]
@abelmenkveld the `top` value from the `useHeaderMeasurements()` hook in v4 is a reanimated2 `SharedValue`. You could use `useAnimatedReaction` or `useDerivedValue` on it to react to changes. See:

https://docs.swmansion.com/react-native-reanimated/docs/next/api/useAnimatedReaction/

**Comment by PedroBern** [comment]
@abelmenkveld in addition to @andreialecu 's answer, you can  create your animation logic inside the header component (to get the context with `useHeaderMeasurements()`) and save it to your own context

```tsx
// in the header component
const { top, height } useHeaderMeasurements()
const style = useAnimatedStyle(...)
saveStyleToMyOwnContext(style) // inside useEffect

// in the navigation bar you want to animate
const { style } = useMyOwnContext()
```

**Comment by abelmenkveld** [comment]
Thanks a lot guys for your great help! Finally got it working with useAnimatedReaction :). One last question: Is there a way to retrieve the contentOffset.y value of a ScrollView/FlatList? I can also create a new issue if this is simply a feature request, since we might need a dedicated hook for this?

In my use case I have a floating "scroll to today" button in a calendar-like list which should hide/show based on the scroll position

**Comment by andreialecu** [comment]
A hook to expose the current Y would be useful indeed. 

Would you like to open a PR for it? It shouldn't be a big change. Take a look at one of the other hooks.
