### ISSUE TITLE
Tabs.Scrollview reports a typescript properties missing error for its children component

### ISSUE THREAD

**Issue by xyxc0673** [PedroBern/react-native-collapsible-tab-view#158]
### Current behavior

Report a error
``` Type '{ children: Element; contentContainerStyle: { shadowOffset: { width: number; height: number; }; elevation: number; }; }' is missing the following properties from type 'Pick<ScrollViewProps, "hitSlop" | "onLayout" | "pointerEvents" | "removeClippedSubviews" | "style" | "testID" | "nativeID" | "collapsable" | "needsOffscreenAlphaCompositing" | ... 96 more ... | "persistentScrollbar">': accessibilityComponentType, accessibilityTraitsts(2739) ```

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

```
<Tabs.Tab name="Info" label="Info">
  <Tabs.ScrollView contentContainerStyle={styles.tabHeaderContainer}>
    <View>
      <Text>123</Text>
    </View>
  </Tabs.ScrollView>
</Tabs.Tab>
```

### What have you tried
- Upgrade typescript version but no help

The app was created by React Native CLI

**Comment by andreialecu** [comment]
See: https://github.com/PedroBern/react-native-collapsible-tab-view/issues/139#issuecomment-782101899
