### ISSUE TITLE
how to add Icons for  tabs

### ISSUE THREAD

**Issue by 034502219988** [PedroBern/react-native-collapsible-tab-view#159]
hi, i need to ask that how can we use icons for tabs, now we are just using label.

**Comment by 034502219988** [comment]
please add option to use icon for tab

**Comment by picknamexd** [comment]
Hello! I would also like this powerful package to include the possibility of adding icons to the tabs, I managed to do it in a more complicated way using custom tabs.

I'm going to show you how I have done it and I hope it helps you!


I have added to my code all the .tsx and .ts of the MaterialTabBar folder, you can find it in the code of this repository,
Then I looked for the place where I put the name of the tab (TabItem.tsx at the end)
and i changed it for these lines of code

```
.......
            android_ripple={{
                borderless: true,
                color: pressColor,
            }}
            {...rest}
        >
            <Animated.Text style={[styles.label, stylez, labelStyle]}>
                <MaterialIcons name={label} size={30}/>
            </Animated.Text>
        </Pressable>
    )
}

const styles = StyleSheet.create({
    grow: {
        flex: 1,
.....
```

As you can see, inside Animated.Text I have removed the {label} tag that there was, and I have added my icon tag, in my case I am using the imported icons from `import MaterialIcons from 'react-native-vector-icons / MaterialIcons' ;`

Later, when adding the tag in Tabs.Tab, you can put the name of the icon that you are going to use example;

```
      <Tabs.Tab name="Photos" label="photo-library">
        <Tabs.FlatList
          data={[0, 1, 2, 3, 4]}
          renderItem={renderItem}
          keyExtractor={(v) => v + ''}
        />
      </Tabs.Tab>
```


I don't think it's the best fix in the world, but I managed to show the tabs! I hope you can get it too

**Comment by PedroBern** [comment]
Probably we can add a `renderIcon` prop on the tabbar, and allow to pass an `icon` prop on the `Tabs.Tab`. This would allow rendering icons + labels

**Comment by 034502219988** [comment]
@PedroBern  thanks, if you can add icons to the next release.

**Comment by leonnardovv** [comment]
Hi, add the following prop to Tab.Navigator:

`tabBarOptions={{showLabel: true, showIcon: true}}`

And the following prop to Tab.Screen:

```
options={{
            tabBarIcon: ({focused}) => (
              <CameraIcon
                height={20}
                width={20}
                fill={COLORS.primaryColor}
                opacity={focused ? 1 : 0.7}
              />
            ),
            tabBarLabel: 'Attractions',
          }}
```

where CameraIcon is a component

@034502219988 @PedroBern

**Comment by kyps2020** [comment]
I've looked in the manual, but I can't find anything about adding icons in the tab bar. anyone have solution for this problem?

**Comment by vlack-coder** [comment]
Honestly, I don't still get this.... I think I'll use what @picknamexd used earlier, only that I'll have to stick to Ionicons till you elaborate on this cuz I can't find anything like collapsible option or Tab.Navigator

**Comment by vlack-coder** [comment]
I'm just getting to know that collapsibleOptions is a prop to createMaterialCollapsibleTopTabNavigator from an older version. I'm seriously stuck here

**Comment by KazakovVS** [comment]
[](url)> Honestly, I don't still get this.... I think I'll use what @picknamexd used earlier, only that I'll have to stick to Ionicons till you elaborate on this cuz I can't find anything like collapsible option or Tab.Navigator

What I did is just created a custom MaterialTabItem component by copying it from the .../node_modules/react-native-collapsible-tab-view/src/MaterialTabBar/TabItem.tsx and replacing the Animated.Text to the desired result.

Then I just passed as a param to the TabBar like this
`TabItemComponent={(itemProps) => <MaterialTabItem
        {...itemProps}
      />`

And the resulting outcome is here
<img width="440" alt="iPhone 13 2021-11-02 11-57-07" src="https://user-images.githubusercontent.com/16006060/139769888-6232434f-c735-47bc-aa5b-59196bff36c2.png">

**Comment by vlack-coder** [comment]
> > Honestly, I don't still get this.... I think I'll use what @picknamexd used earlier, only that I'll have to stick to Ionicons till you elaborate on this cuz I can't find anything like collapsible option or Tab.Navigator
> 
> What I did is just created a custom MaterialTabItem component by copying it from the .../node_modules/react-native-collapsible-tab-view/src/MaterialTabBar/TabItem.tsx and replacing the Animated.Text to the desired result.
> 
> Then I just passed as a param to the TabBar like this `TabItemComponent={(itemProps) => <MaterialTabItem {...itemProps} />`
> 
> And the resulting outcome is here <img alt="iPhone 13 2021-11-02 11-57-07" width="440" src="https://user-images.githubusercontent.com/16006060/139769888-6232434f-c735-47bc-aa5b-59196bff36c2.png">

Thanks..... I also did somewhat the same thing
`     <Animated.Text style={[styles.label, stylez, labelStyle]}>
              <Ionic name={label} size={30}/>
      </Animated.Text>`

On the tab configuration,
`   <Tabs.Container
                renderHeader={Header}
                // headerHeight={3000} // optional
                TabBarComponent={(props) => (
                    <MaterialTabBar
                        {...props}
                        activeColor="red"
                        inactiveColor="grey"
                        // inactiveOpacity={1}
                        labelStyle={{ fontSize: 14 }}
                        // TabItemComponent
                    />
                )}
            >`
then   ` <Tabs.Tab name="A" label="options-outline">`

- First of all, I want to be able to add my custom icon for each tab, not Ionic icons....
- I also want a text label under the icons.... Any suggestions. Thanks in anticipation of your response

![ok](https://user-images.githubusercontent.com/56041655/139771637-98323a14-0e21-4d35-9c66-c929b9d5afa0.jpg)

**Comment by martymfly** [comment]
> MaterialTabItem {...itemProps}

Can you please share the code for your implementation?

**Comment by andreialecu** [comment]
#255 should make this easier. [`51a7234` (#255)](https://github.com/PedroBern/react-native-collapsible-tab-view/pull/255/commits/51a7234fec8f19f384ed771789d883aee247260f)

It's part of `5.0.0-rc.8`. See https://github.com/PedroBern/react-native-collapsible-tab-view/pull/255
