### ISSUE TITLE
Header not showing

### ISSUE THREAD

**Issue by alexpchin** [PedroBern/react-native-collapsible-tab-view#16]
I've just tried to implement the basic example but the header isn't displaying? I'm on:

```
"react-native": "0.63.3"
```

Using: 

```
  const [index, setIndex] = useState(0);

  const [routes] = useState([
    { key: 'first', title: 'First' },
    { key: 'second', title: 'Second' },
  ]);

  const _renderHeader = () => (
    <View style={styles.header}>
      <Text style={styles.headerText}>COLLAPSIBLE</Text>
    </View>
  );

  const _onTabPress = (tabProps) => {
    tabProps.jumpTo(tabProps.route.key);
  };

  const _renderTabBar = (props) => {
    return <TabBar {...props} onTabPress={_onTabPress} />;
  };

  return (
    <CollapsibleTabView
      navigationState={{ index, routes }}
      onIndexChange={setIndex}
      renderHeader={_renderHeader}
      renderScene={SceneMap({
        first: () => null,
        second: () => null,
      })}
      renderTabBar={_renderTabBar}
    />
  );
```

Any ideas?

**Comment by alexpchin** [comment]
It seems like you should include the header in renderTabBar?

```
const [index, setIndex] = useState(0);

  const [routes] = useState([
    {
      icon: (
        <FontAwesomeIcon
          color={C.COLOR_BLACK}
          icon={['fab', 'apple']}
          size={20}
          style={styles.iconStyle}
        />
      ),
      key: 'first',
      title: 'First',
    },
    { key: 'second', title: 'Second' },
  ]);

  const _renderHeader = (props) => (
    <>
      <View style={styles.header}>
        <Text style={styles.headerText}>COLLAPSIBLE</Text>
      </View>
      <TabBar {...props} onTabPress={_onTabPress} />
    </>
  );

  const _onTabPress = (tabProps) => {
    tabProps.jumpTo(tabProps.route.key);
  };

  return (
    <CollapsibleTabView
      navigationState={{ index, routes }}
      onIndexChange={setIndex}
      renderScene={SceneMap({
        first: () => <SomeRoute color="white" routeKey="first" />,
        second: () => <SomeRoute color="black" routeKey="second" />,
      })}
      renderTabBar={_renderHeader}
    />
  );
```

**Comment by PedroBern** [comment]
Hi @alexpchin no, the header shouldn't be included in the tab bar.

Did you forget to add the styles? Assuming you are copying from the quick start example in the readme.

```js
const styles = StyleSheet.create({
  header: {
    height: HEADER_HEIGHT,
    backgroundColor: '#2196f3',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
  },
  headerText: {
    color: 'white',
    fontSize: 24,
  },
  content: {
    height: 1500,
  },
});
```

**Comment by alexpchin** [comment]
Hi @PedroBern I do appreciate that this issue seems like I haven't followed the installation instructions... I promise I'm not simple ;)  I am adding to an existing react-native application.

Firstly, to get up and running I had to install `@react-navigation/material-top-tabs`. Whilst I do have react-navigation running in the project, it seemed from the README that you only had to do this if you were integrating with react-navigation rather than just using the component on a screen.

I will investigate further and perhaps create a demo to share on CodeSandbox or something.

Question - If the content of one of the tabs is shorter than the other, are the tabs meant to stick at the top?

Thanks,
Aleex

**Comment by alexpchin** [comment]
FYI,  a small update. The issue is when you omit the `headerHeight` which the docs say is _optional_. I checked the code in your example. If you comment out `CollapsibleTabViewDemoExample`, you will see the issue I was facing.

```js
return (
    <CollapsibleTabView
      // headerHeight={HEADER_HEIGHT} // optional, will be computed.
      navigationState={{ index, routes }}
      onIndexChange={handleIndexChange}
      renderHeader={renderHeader}
      renderScene={renderScene} 
    />
  );
```

Thanks!

**Comment by PedroBern** [comment]
> FYI, a small update. The issue is when you omit the `headerHeight` which the docs say is optional. I checked the code in your example. If you comment out `CollapsibleTabViewDemoExample`, you will see the issue I was facing.

That's weird, it does not happen here. I've just commented out, I get the same behavior as before.

> Question - If the content of one of the tabs is shorter than the other, are the tabs meant to stick at the top?

Do you mean the tab or the screen of the tab? If you have a tab screen smaller than the window, you can see [small content example](https://github.com/PedroBern/react-native-collapsible-tab-view/blob/main/example/src/CollapsibleTabViewSmallContentExample.tsx).

> I will investigate further and perhaps create a demo to share on CodeSandbox or something.

Perfect, if can do that I appreciate :)

**Comment by alexpchin** [comment]
Thank you for the heads up on the small content example.

So far my steps: 

- I forked the repo. 
- Loaded the packages in example with yarn. 
- Ran the example using ios simulator. (Everything worked ok). 
- Commented out the line about `headerHeight` which causes the header not to appear.

Interestingly, the header works fine if the value is:

```js
headerHeight={1}
```

The line in `CollapsibleTabView`: 

```js
{headerHeight > 0 && renderHeader()}
```

If the default `headerHeight` is 0 and there is no headerHeight provided by props, if `renderHeader` has been provided then a header will render, if not then you'll render null... So can you not just omit this check?

```js
{renderHeader()}
```

**Comment by PedroBern** [comment]
> Thank you for the heads up on the small content example.

It will be handled inside the package in the next release with #17

Regardings the header height, I will check it today and come back here.

**Comment by PedroBern** [comment]
> UPDATE2 ...

The `48` is the `minHeight`. You can check the real `tabBarHeight` with the following code in your fork. We need to chose between computing the real `tabBarHeight` or `headerHeight` onLayout, we can't guess both, only if one of then is provided, in this case, I choose to always have `tabBarHeight`, allowing to render a header without up front height.

Add this to your fork, in the `CollapsibleTabView.tsx`.

```tsx
const getHeaderHeight = React.useCallback(
    (event: LayoutChangeEvent) => {
      const value = event.nativeEvent.layout.height - tabBarHeight;
      console.log(value - 250) // 250 is the header height from the example. It will log the real tabBarHeight, around 49.xx
      ....
```

**Comment by PedroBern** [comment]
I get `49.428558349609375`.

Check out #18, at any moment the preview will be ready. Or see [the code](https://github.com/PedroBern/react-native-collapsible-tab-view/pull/18/commits/534aa58b13d4d5f923de794eaa85a5329ef854b9) and try to implement by yourself to see if works. I don't have access to iOS simulator right now, so I couldn't tell.

**Comment by alexpchin** [comment]
Hi @PedroBern Thanks! I've just fetched #18 and the problem still occurs. I will look at a possible solution now.

**Comment by PedroBern** [comment]
@alexpchin thanks, please if you solve share it here or open a PR :)

**Comment by alexpchin** [comment]
Hello @PedroBern From what I can tell, I think this is working:

```js
const getHeaderHeight = React.useCallback(
    (event: LayoutChangeEvent) => {
      const value = event.nativeEvent.layout.height - tabBarHeight;
      if (Math.round(value * 10) / 10 !== Math.round(headerHeight * 10) / 10) {
        onHeaderHeightChange?.();
        setHeaderHeight(Math.max(value, 0));
        setTranslateY(
          scrollY.interpolate({
            inputRange: [0, Math.max(value, 0)],
            outputRange: [0, -value],
            extrapolateRight: 'clamp',
          })
        );
      }
    },
    [headerHeight, onHeaderHeightChange, scrollY, tabBarHeight]
  );
```

Accompanied by:

```js
{renderHeader()}
```

**Comment by PedroBern** [comment]
Of course! Already pushed to #18

**Comment by PedroBern** [comment]
Solved in `v1.3.1`, with #18

**Comment by alexpchin** [comment]
👍🏻 Kudos on the library by the way. Nice work!

**Comment by PedroBern** [comment]
Thanks :) please let me know if you find more problems
