### ISSUE TITLE
dependencies not updated when firing onTabChange  

### ISSUE THREAD

**Issue by xyxc0673** [PedroBern/react-native-collapsible-tab-view#161]
Hi guys , thanks for the great package.

I have a problem.

code like these:
```
const handleTabChange = (homeTopicMap: any, tabName: string) => {
  if (!homeTopicMap[tabName]) {
    dispatch(fetchTopicByTab({ tab: tabName as string, refresh: false }));
  }
};
```
the verb homeTopicMap was not updated when redux state has been updated.

how do I make it work with the homeTopicMap?

**Comment by andreialecu** [comment]
Sorry, but this question is quite generic and doesn't seem about `react-native-collapsible-tab-view` so I'm not sure how to help here.
