### ISSUE TITLE
Upgrade reanimated to stable + upgrade example app to expo SDK 41

### ISSUE THREAD

**Issue by PedroBern** [PedroBern/react-native-collapsible-tab-view#164]

**Comment by tgwow** [comment]
which version of sdk and react-reanimated is recommended to use this incredible lib?
I was using SDK 40 and reanimated `2.0.0-rc.2`, but I got a multiple thread usage error: `I tried to call the {assign} synchronous call function from a different thread`
I also tried version `2.0.0-rc.0` and got the error `_setGlobalConsole`. I cleared the cache and all the steps suggested in these [#1640](https://github.com/software-mansion/react-native-reanimated/issues/1640), [#1546](https://github.com/software-mansion/react-native-reanimated/issues/1546) threads, but none of them works.
Do you know what I could do? I really wanted to use this lib: c

**Comment by PedroBern** [comment]
Hi @tgwow please see the package.json file in the root folder and the expo SDK version of the example app.

If you need the upgrade, you can work on a PR to make this lib compatible with the latest stable reanimated and upgrade the example app. This would be very appreciated 🎉

**Comment by yonjuukyuu** [comment]
Hi,
`"expo": "~40.0.0",`
`react-native-reanimated": "^2.1.0",`

Im getting this _setglobalConsole_f error as well for a while now, have try the reset cash and reinstalle modules noone seem to work, is there a workaround this yet ?

I do have the plugin in babel config too.

**Comment by alexco2** [comment]
Included in this pr: https://github.com/PedroBern/react-native-collapsible-tab-view/pull/201
