### ISSUE TITLE
createMaterialCollapsibleTopTabNavigator not found in 'react-native-collapsible-tab-view'

### ISSUE THREAD

**Issue by sierradean** [PedroBern/react-native-collapsible-tab-view#166]
I am attempting to use the TabNavigator wrapper for the collapsible header. However, I run
`npm install react-native-collapsible-tab-view`
and my import looks like this (how I import everything else for the project
`import {createMaterialCollapsibleTopTabNavigator} from 'react-native-collapsible-tab-view'`
When attempting to initialize the navigator (const Tab = createMaterialCollapsibleTopTabNavigator();) I receive the attached error:
<img width="389" alt="Screen Shot 2021-04-20 at 1 05 30 PM" src="https://user-images.githubusercontent.com/43556526/115457257-207d7480-a1d9-11eb-9dd5-4aca03d64f45.png">

I attempted to console log the createMaterialCollapsibleTopTabNavigator function and it return with undefined, hence the function is not found in the package. Did I install wrong? I have additionally installed all the dependencies as follows:
`from package.json
 "react-native-reanimated": "~1.9.0",
"@react-navigation/material-top-tabs": "^5.2.10",
 "@react-navigation/native": "^5.4.0",
 "react-native-tab-view": "^2.15.2",
`
 I am currently using npm as my package manager instead of yarn, does the installation only work with yarn?

Any guidance would be greatly appreciated. I qualified this as a question as compared to a bug as I feel it is a problem with my implementation not with the package. 

Thank you!

**Comment by andreialecu** [comment]
Hey @sierradean the current version does not have react navigation support built in yet.

I have a work in progress implementation which I'm going to share here:
https://gist.github.com/andreialecu/3843786a4b849c33b559963656467f2f

You can simply drop it into your project and use it like:

```tsx
import createCollapsibleNavigator from './create-collapsible-navigator';

const Tab = createCollapsibleNavigator();

export function SomeComponent() {
  return (
	    <Tab.Navigator
	      collapsibleOptions={{
	        lazy: true,
	        tabBarHeight: styles.tabBar.height,
	        headerHeight: styles.headerContainer.minHeight,
	        renderHeader: () => (
	          <YourHeader />
	        ),
	        renderTabBar: (props) => (
	          <MaterialTabBar
	            {...props}
	            //scrollEnabled
	          />
	        ),
	      }}
	    >
	      <Tab.Screen
	        name="info"
	        options={{
	          title: 'Info',
	        }}
	      >
	        {() => <Info />}
	      </Tab.Screen>
          // other screens here
  		</Tab.Navigator>
```

**Comment by sierradean** [comment]
Ah thank you! I misunderstood the documentation. I will try that out!

**Comment by Jamal-ReachFirst** [comment]
Re-open this issue until it is fixed and pushed to the package.

**Comment by RobertUpchurch** [comment]
Is this still not available in newer versions?

**Comment by zguo123** [comment]
I do think this was removed, as it was implemented before here: 

https://github.com/PedroBern/react-native-collapsible-tab-view/commit/e34a34b8ef2fb498be1afbbfb292154265ee7ece and here: https://github.com/PedroBern/react-native-collapsible-tab-view/issues/7
