### ISSUE TITLE
if you want to use Reanimated 2 then go through our installation steps

### ISSUE THREAD

**Issue by Kasheeram** [PedroBern/react-native-collapsible-tab-view#168]
I am integration this library for collapsable header tab, Also i have install react-native-reanimated v2, still getting this error, please help me.

if you want to use Reanimated 2 then go through our installation steps https://docs.swmansion.com/react-native-reanimated/docs/installation

package.json
```json
"dependencies": {
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/cli-platform-android": "^4.13.0",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/bottom-tabs": "^5.11.8",
    "@react-navigation/drawer": "^5.12.5",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.4",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-collapsible-tab-view": "^4.2.0-pre.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-paper": "^4.7.2",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.1.1",
    "react-native-see-more-inline": "^1.3.0",
    "react-native-text-size": "^4.0.0-rc.1",
    "styled-components": "^5.2.3"
  },
```
![Simulator Screen Shot - iPhone 12 - 2021-04-29 at 09 18 00](https://user-images.githubusercontent.com/19978447/116682455-e6c41f00-a9cb-11eb-97ac-84cf5bbd7e15.png)

**Comment by andreialecu** [comment]
Did you add the babel plugin as mentioned in the link?

**Comment by Kasheeram** [comment]
Yes i added,

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};

**Comment by Kasheeram** [comment]
Its working when i am creating fresh new  App but not working with existing App.

**Comment by andreialecu** [comment]
Did you install the pods? `cd ios && pod install`

**Comment by Kasheeram** [comment]
Yes i did  cd ios && pod install after installing "react-native-collapsible-tab-view"

**Comment by AuroreUX** [comment]
I have the same issue here !
Anyone has a tip to resolve this issue?
I'm going to keep working with Animated from react native :(((((

**Comment by andreialecu** [comment]
I'm going to close this because it's not an issue with this library. Feel free to post the solution once you find it.

I suggest having a look at how the check works here: https://github.com/software-mansion/react-native-reanimated/blob/a8d9720ee5312a43cc4e3beb02e70b2fc6a030ae/src/reanimated2/core.ts#L23-L45 and checking what's going wrong with it.

Alternatively take a look at https://github.com/software-mansion/react-native-reanimated/issues/1875 or open an issue in the reanimated repo.

**Comment by sunzhongliangde** [comment]
https://github.com/software-mansion/react-native-reanimated/issues/1875#issuecomment-857601710

see this, it works for me

**Comment by noway** [comment]
I deleted the app and installed it again and it worked.

**Comment by DavydVeremchuk** [comment]
I have already installed a `react-native-reanimated` of `2.2.0` version and everything had been working fine until yesterday my app randomly crashed with this error.

package.json
`
"dependencies": {
    "@ptomasroos/react-native-multi-slider": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.15.5",
    "@react-native-community/eslint-config": "3.0.0",
    "@react-native-firebase/app": "^12.4.0",
    "@react-native-firebase/auth": "^12.4.0",
    "@react-native-firebase/database": "^12.4.0",
    "@react-native-firebase/dynamic-links": "^12.4.0",
    "@react-native-firebase/messaging": "^12.4.0",
    "@react-native-firebase/storage": "^12.4.0",
    "@react-navigation/bottom-tabs": "^6.0.3",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/native-stack": "^6.0.4",
    "@react-navigation/stack": "^6.0.4",
    "axios": "^0.21.1",
    "buffer": "^6.0.3",
    "crypto-js": "^4.1.1",
    "events": "^3.3.0",
    "husky": "^7.0.1",
    "pbkdf2": "^3.1.2",
    "qs": "^6.10.1",
    "react": "17.0.2",
    "react-native": "0.64.2",
    "react-native-config": "^1.4.3",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-get-random-values": "^1.7.0",
    "react-native-reanimated": "^2.2.0",
    "react-native-safe-area-context": "^3.3.0",
    "react-native-screens": "^3.5.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.1",
    "react-native-swiper": "^1.6.0",
    "react-navigation": "^4.4.4",
    "react-redux": "^7.2.4",
    "redux": "^4.1.1",
    "redux-saga": "^1.1.3",
    "uuid": "^8.3.2",
    "yup": "^0.32.9"
  }, 
`
babel.config.js
`
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin'],
};
`

Podfile
`
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
target 'MoxieGirl' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'MoxieGirlTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    fix_deployment_target(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
    end
  end
  
  def fix_deployment_target(installer)
      if !installer
          return
      end
      puts "Make the pods deployment target version the same as our target"
      
      project = installer.pods_project
      deploymentMap = {}
      project.build_configurations.each do |config|
          deploymentMap[config.name] = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      end
      # p deploymentMap
      
      project.targets.each do |t|
          puts "  #{t.name}"
          t.build_configurations.each do |config|
              oldTarget = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
              newTarget = deploymentMap[config.name]
              if oldTarget == newTarget
                  next
              end
              puts "    #{config.name} deployment target: #{oldTarget} => #{newTarget}"
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = newTarget
          end
      end
  end
end
`

**Comment by naheed-shamim** [comment]
Reanimated 2 doesn't work in Debug mode. Stop your debugging mode and it should work.

**Comment by fernandoVicentei** [comment]
> Reanimado 2 no funciona en el moIn other words, dear, the error will disappear when the publication is published in an app store?do de depuración. Detenga su modo de depuración y debería funcionar.

**Comment by Mogul123** [comment]
> Reanimated 2 doesn't work in Debug mode. Stop your debugging mode and it should work.

That was the solution for me! Thanks!

**Comment by h1nson** [comment]
Hi guys, finally i solved this issue by install **react-native-reanimated@alpha**,  do not use **react-native-reanimated@next**!

**Comment by pycraft114** [comment]
'Reanimated 2 doesn't work in Debug mode. Stop your debugging mode and it should work.' This should be documented

**Comment by Andzie-M347** [comment]
> Reanimated 2 doesn't work in Debug mode. Stop your debugging mode and it should work.

Thanks, this was my issue.

**Comment by hokimtam** [comment]
> Reanimated 2 doesn't work in Debug mode. Stop your debugging mode and it should work.

where is document ?
