### ISSUE TITLE
How to add pull to refresh?

### ISSUE THREAD

**Issue by lyseiha** [PedroBern/react-native-collapsible-tab-view#173]

**Comment by andreialecu** [comment]
Take a look at https://github.com/PedroBern/react-native-collapsible-tab-view/blob/83250045e6e9f65f35cb71276fc53337182e3eb4/example/src/Shared/Albums.tsx

The example app has pull to refresh functionality on all tabs.

**Comment by lyseiha** [comment]
Is it support for un-expo project?

**Comment by anhquan291** [comment]
Hi @andreialecu 
About pull to refresh, I'm facing a problem on iOS when using the Tabs.Flatlist in a Bottom Tab.  After the List fetch items for the first time, I press to another BottomTab, and I then go back to the Tab that using Tabs.Flatlist, the Refresh Icon was there. So strange. Any suggestions please? Thank you so much.
![Simulator Screen Shot - iPhone 11 Pro - 2022-02-20 at 21 57 58](https://user-images.githubusercontent.com/17813202/154848972-2b9f6240-5518-41ea-b3b5-646accae51b0.png)

**Comment by Chasty** [comment]
Hi @anhquan291 any solution on that, I'm facing same issue

**Comment by rajeshde** [comment]
I am facing the same issue @anhquan291 @Chasty . Have you find any workaround or solution to this?
