### ISSUE TITLE
Can we apply the collapsible animation to our own react native flatlist ?

### ISSUE THREAD

**Issue by mehthabux** [PedroBern/react-native-collapsible-tab-view#174]
can we have any hooks to used to animate  the  header when  react native flatlist is used ?

**Comment by andreialecu** [comment]
The library does wrap a normal RN FlatList and attaches some custom hooks, take a look at: https://github.com/PedroBern/react-native-collapsible-tab-view/blob/main/src/FlatList.tsx

What is your use case?

**Comment by mehthabux** [comment]
yes, i noticed . my issue got solved 
thank you 👍
