### ISSUE TITLE
useTabsContext must be inside a Tabs.Container

### ISSUE THREAD

**Issue by SiSa68** [PedroBern/react-native-collapsible-tab-view#175]
Hi there
I just tested your example on non-expo react native and it crashes in `AnimatedHeader` example with this error:

`Error: useTabsContext must be inside a Tabs.Container`

**Comment by Punit-Vajpeyi** [comment]
@SiSa68 replace following line

  `HeaderComponent={Header}

with

  `HeaderComponent={props => <Header {...props} />}

It worked for me

**Comment by andreialecu** [comment]
Indeed the example was wrong, fixed in #177
