### ISSUE TITLE
Styling the Tabs Labels

### ISSUE THREAD

**Issue by adelaadeoye** [PedroBern/react-native-collapsible-tab-view#176]
Please is there anyone who could assist in styling the labels for the Tabs .

This is what I have at the moment 
```tsx
 <Tabs.Tab
          name="Schedule"
          label="Schedules"
          labelStyle={{
            color: 'red',
            fontSize: 8,
          }}>
```
But it is not working

**Comment by andreialecu** [comment]
Upgrade to version `4.2.0` so that `renderTabBar` is available:

Example:
```tsx
<Tabs.Container renderTabBar={(props) => (
            <MaterialTabBar
              {...props}
              style={...}
              labelStyle={...}
              indicatorStyle={...}
              scrollEnabled={true/false}
            />} ...
```

**Comment by adelaadeoye** [comment]
> Upgrade to version `4.2.0` so that `renderTabBar` is available:
> 
> Example:
> 
> ```tsx
> <Tabs.Container renderTabBar={(props) => (
>             <MaterialTabBar
>               {...props}
>               style={...}
>               labelStyle={...}
>               indicatorStyle={...}
>               scrollEnabled={true/false}
>             />} ...
> ```

Thanks, A colleague provided me with this and it work
```
<Tabs.Container
        TabBarComponent={(props) => (
          <MaterialTabBar
            {...props}
            activeColor={Colors.AmberRed}
            labelStyle={{fontSize: 9, fontWeight: 'bold'}}
            indicatorStyle={{backgroundColor: Colors.AmberRed}}
          />

```    and it also
