### ISSUE TITLE
On change the tab indication colour does not show for next tab only in RTL ( for HEBREW language)

### ISSUE THREAD

**Issue by saurabh874** [PedroBern/react-native-collapsible-tab-view#179]
@PedroBern  do you have any idea how to resolve it ? even i tried to change in node_module but did not get any solution.
<img width="1440" alt="Screenshot 2021-06-04 at 20 51 25" src="https://user-images.githubusercontent.com/59818553/120825056-a29dde80-c576-11eb-9ae0-b3b3d21675b8.png">

**Comment by andreialecu** [comment]
The coordinates here may need to be adjusted when using RTL: 
https://github.com/PedroBern/react-native-collapsible-tab-view/blob/ebfecd77ebd50cae30f8b911202a068e41b5efd4/src/MaterialTabBar/Indicator.tsx#L25

If you come up with a solution please submit a PR.

**Comment by andreialecu** [comment]
Related: https://github.com/facebook/react-native/issues/29060

**Comment by andreialecu** [comment]
I believe this may have been fixed in 4.3.0 after merging #193 

Will close, but feel free to open a new issue if the problem persists.

**Comment by Abderrahmane-K** [comment]
@andreialecu did you find a solution for this problem?

**Comment by andreialecu** [comment]
Try the new v5 rc.
