### ISSUE TITLE
Tabs.Container in a screen without screen header causing unlikely shadow on top of the screen

### ISSUE THREAD

**Issue by elirangoshen** [PedroBern/react-native-collapsible-tab-view#183]
### Current behavior

When im using Tab.Container in a screen that im using custom screen header, i notice there is some shadow line in the top

### Expected behaviour

there shouldn't be any shadow in the top of the screen

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

>

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/9560116/121478942-d4c19d00-c9c9-11eb-9e1b-24915fb275df.png)

### What have you tried

I tried to change Tab.Container props but still couldn't solve it

**Comment by andreialecu** [comment]
This is caused by these default styles:

https://github.com/PedroBern/react-native-collapsible-tab-view/blob/73af1692f88de0c525ebc6440ed592a5ff7e4fcf/src/Container.tsx#L548-L561

You can use the `headerContainerStyle` prop to override them.

**Comment by elirangoshen** [comment]
thanks ! it worked

**Comment by rahulrj25** [comment]
Setting shadowOpacity: 0 did the job for me

**Comment by rahulrj25** [comment]
@andreialecu shadowOpacity: 0 worked for ios, can you tell me how to achieve same for android? Also in android on pressing tabs ripple effect shows, how to disable that?

**Comment by acro5piano** [comment]
Full example:

```tsx
const styles = StyleSheet.create({
  headerContainerStyle: {
    shadowOpacity: 0,
  },
});

  <Tabs.Container
    headerContainerStyle={styles.headerContainerStyle}
    // ...
```

May not work with Android
