### ISSUE TITLE
when swiping i cannot see the focused tab indicationl

### ISSUE THREAD

**Issue by elirangoshen** [PedroBern/react-native-collapsible-tab-view#188]
when i swipe the tabs i cannot see the new tab indication. it is swipe to the new tab but the header is not changing.
is there an attribute i need to add to solve it ? 

i'm using custom tab bar. 
in pics you can see that when i press the tab label its ok but when i swipe its not showing the tab label indication

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-23 at 11 45 17](https://user-images.githubusercontent.com/9560116/123075459-8aeca400-d418-11eb-9212-e83fc67685d6.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-23 at 11 45 20](https://user-images.githubusercontent.com/9560116/123075475-8e802b00-d418-11eb-864d-771f9a628d80.png)
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-23 at 11 45 25](https://user-images.githubusercontent.com/9560116/123075484-90e28500-d418-11eb-8659-87311ddd8dd4.png)

**Comment by andreialecu** [comment]
Try #186 , there's a comment on how to install it there.

**Comment by elirangoshen** [comment]
is the new version should solve this bug ? :)

**Comment by andreialecu** [comment]
4.2.1 has been released. Please check if it happens on it and I can reopen.
