### ISSUE TITLE
Gap between header and content if lazy === true

### ISSUE THREAD

**Issue by PedroBern** [PedroBern/react-native-collapsible-tab-view#19]
### Current behavior

`<CollapsibleTabView  lazy ...>` do not sync scroll position of unmounted routes, as expected, because the routes are unmounted! But, when the routes are mounted, may start with a gap between the header and the content.

### Expected behaviour

When mounting the lazy routes, they should know the header position and start with the correct scroll position.

### Workaround

The current workaround is to handle the laziness by yourself. What actually can be a good thing, since the lazy prop of `react-native-tab-view` is pseudo-lazy. It loads all routes if you click on the last tab!

**Comment by Janak-Nirmal** [comment]
@PedroBern Is there any solution to fix this issue, using lazy={true} is necessary if we don't want to load all the data until user really visits that tab.

**Comment by PedroBern** [comment]
> @PedroBern Is there any solution to fix this issue, using lazy={true} is necessary if we don't want to load all the data until user really visits that tab. 

@Janak-Nirmal  as I wrote above:

> The current workaround is to handle the laziness by yourself. What actually can be a good thing, since the lazy prop of react-native-tab-view is pseudo-lazy. It loads all routes if you click on the last tab!
