### ISSUE TITLE
Can we have scroll on header while having buttons in header?

### ISSUE THREAD

**Issue by iarmankhan** [PedroBern/react-native-collapsible-tab-view#194]
So I went through the examples and found what I need in 'ScrollOnHeader' example. The only problem is we can't have any kind of pressable or touchable stuff in it, because of `pointerEvents="none"` on surrounding view. Do we have any other way to like get this working? Thank you.

**Comment by iarmankhan** [comment]
I should'd read the docs properly before asking. It is there in docs. Sorry for this.

For anyone wondering the same. It is here [Scroll on header](https://github.com/PedroBern/react-native-collapsible-tab-view#scroll-on-header)

**Comment by metinaltinbas** [comment]
@iarmankhan pointerevents deosn't work properly as it should be
