### ISSUE TITLE
Very weird behavior in Android RTL & iOS

### ISSUE THREAD

**Issue by mustafaskyer** [PedroBern/react-native-collapsible-tab-view#197]
Hello,
Thanks for your great work here, really appreciated it!
I tried to run the expo examples on an android device, and I had to update the mode to be in `RTL` mode
then I found more than an unexpected behavior like below:
- indicator doesn't work as expected
- default tab bar has a weird position, also its data is swiped with the last index tab data
- tabs items are not in order (reversed)

NOTE:
RTL in ios doesn't work as expected, especially in indicator when try to swipe from one tab to another

Regards!

**Comment by andreialecu** [comment]
Hello @mustafaskyer 

I merged your PR in #193 so hopefully this is resolved. If not, feel free to ping me to reopen.
