### ISSUE TITLE
Shared Pull To Refresh

### ISSUE THREAD

**Issue by alexpchin** [PedroBern/react-native-collapsible-tab-view#20]
### Feature request

You may want to implement a pull to refresh that is shared across all tabs. This might just be good to be included in the examples.

### Current behavior

Currently, the examples load a pullToRefresh from each tab's scene independently. I.e. if you do not implement a pull to refresh on each tab, then depending on what tab you are on you you'll get different behaviour.

TAB
- Scene1: FlatList with images
- Scene2: Static user information
- Scene3: ScrollView with other information

### Proposed solution

A shared pullToRefresh that implements a "refreshing" value that can be used trigger a `useEffect` in each scene.

**Comment by PedroBern** [comment]
@alexpchin we definitely can benefit from a shared pull to refresh example. Would you like to implement it in a new example? Or do you think we should completely replace the current behavior? 

I'm also want to add an example for #19

**Comment by alexpchin** [comment]
@PedroBern I'll start exploring some options today.

**Comment by PedroBern** [comment]
@alexpchin I think the easiest way is to create a context with value something like this:

```ts
type RefreshingContext = {
    isRefreshing: boolean
    setRefreshing: (value: boolean) => void
}
```

Then, consume the context inside each tab. All tabs can start refreshing, triggering the `useEffect` on the others.

To create the context, there is this helper `createCtx` from `./src/CollapsibleTabViewContext`, it's not exported, so we need to either copy or export:

```tsx
const [useRefreshingContext, RefreshingContextProvider] = createCtx<
  RefreshingContext
>();
```

What do you think?
