### ISSUE TITLE
onScroll and some other props of ScrollView are not available

### ISSUE THREAD

**Issue by Damon-Zhong** [PedroBern/react-native-collapsible-tab-view#203]
### Feature request

As the doc suggests Tabs.ScrollView should function like a normal ScrollView, but currently there are some props missing. 

### Current behavior

onScroll is missing and onScrollBeginDrag, onScrollAnimationEnd are not functioning when there is nested FlatList/ScrollView within Tabs.ScrollView/Tabs.FlatList

### Screenshots (if applicable)

Repro code snippet:
`import React from "react";
import { View, StyleSheet, FlatList, Text } from "react-native";
import { Tabs } from "react-native-collapsible-tab-view";

const HEADER_HEIGHT = 250;

const Header = () => {
	return <View style={styles.header} />;
};

const App: React.FC = () => {
	return (
		<Tabs.Container
			renderHeader={Header}
			headerHeight={HEADER_HEIGHT} // optional
		>
			<Tabs.Tab name="B">
				<Tabs.ScrollView
					accessibilityComponentType="MyApp"
					accessibilityTraits="scrollable"
					onScrollBeginDrag={() => console.log("onScrollBeginDrag")}
					onScrollAnimationEnd={() => console.log("onScrollAnimationEnd")}
					onScroll={() => console.log("onScroll not exposed")}
				>
					<FlatList
						data={[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]}
						onScroll={() => console.log("onScroll FlatList")}
						keyExtractor={(item) => item.toString()}
						renderItem={({ item }) => (
							<View
								style={{
									flex: 1,
									height: 120,
									borderWidth: 1,
									marginVertical: 5,
								}}
							>
								<Text>{item}</Text>
							</View>
						)}
					/>
					<View style={[styles.box, styles.boxA]} />
					<View style={[styles.box, styles.boxB]} />
				</Tabs.ScrollView>
			</Tabs.Tab>
		</Tabs.Container>
	);
};

const styles = StyleSheet.create({
	box: {
		height: 250,
		width: "100%",
	},
	boxA: {
		backgroundColor: "white",
	},
	boxB: {
		backgroundColor: "#D8D8D8",
	},
	header: {
		height: HEADER_HEIGHT,
		width: "100%",
		backgroundColor: "#2196f3",
	},
});

export default App;
`

**Comment by ianfelix** [comment]
I have the same problem, did you solve it?

**Comment by Hirbod** [comment]
Well you can't just overwrite onScroll here. U need to use the provided hooks and methods if you want to trigger events on scroll.

https://github.com/PedroBern/react-native-collapsible-tab-view/blob/main/src/ScrollView.tsx#L115
As you can see, onScroll is set AFTER `...rest`, so it will overwrite your onScroll method.

These event's are needed to make all the collapsible magic happen here.

**Comment by linweiboy** [comment]
> Well you can't just overwrite onScroll here. U need to use the provided hooks and methods if you want to trigger events on scroll.
> 
> https://github.com/PedroBern/react-native-collapsible-tab-view/blob/main/src/ScrollView.tsx#L115 As you can see, onScroll is set AFTER `...rest`, so it will overwrite your onScroll method.
> 
> These event's are needed to make all the collapsible magic happen here.

I need to monitor which Hooks scrollY should use in real time
