### ISSUE TITLE
Is it possible to have pull to refresh on <Tabs.Container> ?

### ISSUE THREAD

**Issue by jakobsuckow** [PedroBern/react-native-collapsible-tab-view#209]
Hello,
Is it currently possible to implement a refreshControl on the top level container so that I can pull to refresh within my flatlist inside the <Tabs.Tab> and it will pull to refresh at the top ? Basically, just like instagram does it. 

This is my code:
`        <Tabs.Container
          renderHeader={Header}
          headerHeight={HEADER_HEIGHT}
          headerContainerStyle={{
            borderColor: "#000",
            shadowOpacity: 0,
          }}
          containerStyle={{ shadowOpacity: 0, borderBottomColor: "#000" }}
          renderTabBar={props => <MaterialTabBar {...props} />}>
          <Tabs.Tab name="Gallery">
            <Tabs.FlatList
              data={data}
              renderItem={renderItem}
              keyExtractor={v => v + ""}
              bounces={false}
            />
          </Tabs.Tab>
          <Tabs.Tab name="B">
            <Personal />
          </Tabs.Tab>
        </Tabs.Container>`

Thanks so much :)

**Comment by 10000multiplier** [comment]
I'm interested too.

**Comment by andreialecu** [comment]
Not sure if I understand the issue exactly but see #228 or https://github.com/PedroBern/react-native-collapsible-tab-view/blob/main/example/src/AndroidSharedPullToRefresh.tsx

**Comment by Jamal-ReachFirst** [comment]
Unable to reveal header after adding **`RefreshControl`,** on **android** `allowHeaderOverscroll={true}`

Reopen this issue until it is resolved.

**Comment by azwinlam** [comment]
```
        <Tabs.Tab name="Photos"> 
           <Tabs.ScrollView 
             onMomentumScrollEnd={() => {}} 
             showsVerticalScrollIndicator={false} 
             refreshControl={ 
               <RefreshControl refreshing={refreshing} onRefresh={onRefresh} /> 
             } 
           > 
             <PhotoTab 
               restInfo={restInfo} 
               language={language} 
               navigation={navigation} 
             /> 
           </Tabs.ScrollView> 
         </Tabs.Tab>
```

**Comment by Jamal-ReachFirst** [comment]
@azwinlam I want to add refresh on `<Tabs.Container>` not inside tabs

```
<ScrollView
     refreshControl={<RefreshControl ... />}>
   <Tabs.Container>
     //.............
   </Tabs.Container>
</ScrollView
```

It only refreshes not revealing the header

**Comment by Arise-cn** [comment]
iOS

> 不确定我是否完全理解这个问题，但请参阅[＃228](https://github.com/PedroBern/react-native-collapsible-tab-view/pull/228)或https://github.com/PedroBern/react-native-collapsible-tab-view/blob/main/example/src/AndroidSharedPullToRefresh.tsx

refreshControl not show on ios
