### ISSUE TITLE
Error after upgrading to expo 43 in iOS in release mode

### ISSUE THREAD

**Issue by cbarceloc** [PedroBern/react-native-collapsible-tab-view#210]
Everything worked until I updated to expo 43. The app crashes caused to this exception: If you want to use react-native-reanimated 2 then go through our installation steps. I use react-native-reanimated 2 in other parts of my project and it works fine, but I don't know why it crashes when using and visiting the screen where it is located react-native-collapsible-tab-view.  I use 
react-native-collapsible-tab-view v.4.4.0 and react-reanimated 2.0.0.

This error only happens when trying a new release version in iOS (debug version in iOS and both versions in Android work fine)

**Comment by andreialecu** [comment]
Odd. Not sure how this would be related to this library. Try deleting your `node_modules` and maybe all lock files.

Do you use `yarn` or `npm`?

**Comment by cbarceloc** [comment]
oh yes sorry, I've seen it's an issue between expo 43 and react-native-reanimated. Using react-native-reanimated directly in my project also throws the error. I cleared all yarn and pods cache, but it does not seem to be the problem.
https://github.com/expo/expo/issues/14746. Thank you!
