### ISSUE TITLE
Can i use Custom ListView?

### ISSUE THREAD

**Issue by waheed25** [PedroBern/react-native-collapsible-tab-view#212]
I am already using [recyclerlistview](https://github.com/Flipkart/recyclerlistview) and don't want to use Flatlist due to performance issues of list having images, Is there a way to use that [recyclerlistview](https://github.com/Flipkart/recyclerlistview) instead of Flatlist?

**Comment by 10000multiplier** [comment]
This is a duplicate issue. See https://github.com/PedroBern/react-native-collapsible-tab-view/issues/195

**Comment by siddharth-kt** [comment]
Did you got any solution ?

**Comment by waheedakhtar694** [comment]
@siddharth-kt  No.

**Comment by andreialecu** [comment]
Closing as duplicate of #195
