### ISSUE TITLE
Optimize Tabs.FlatList for react navigation modal

### ISSUE THREAD

**Issue by 10000multiplier** [PedroBern/react-native-collapsible-tab-view#215]
### Feature request

When the user scrolls to the top of the `<Tabs.FlatList />` component, the `pointerEvents`  prop should be set to "none," so that the user can keep scrolling to interact with the parent modal screen (i.e. closing the modal by scrolling down) .

### Current behavior

When scrolling inside the `<Tabs.FlatList />`, the user is unable to interact with the parent modal screen.

### Possible solution

```jsx
import { Flatlist } from `react-native-gesture-handler`
```

**Update**: just tried this and it didn't work

### Screenshots (if applicable)

https://user-images.githubusercontent.com/57633368/142478807-0b252ea1-5883-4158-a917-41a5396a13f8.MOV

**Comment by andreialecu** [comment]
I think this is generally a React Navigation issue. See: https://github.com/react-navigation/react-navigation/issues/7154

Not sure if there's anything we can do here.
