### ISSUE TITLE
Tab Indicator size based on dynamic Tab Item Width

### ISSUE THREAD

**Issue by JaitenThomas** [PedroBern/react-native-collapsible-tab-view#217]
### Feature request

Wanting the Tab Indicator size to be dynamic based Tab Item width, similar to twitter

### Current behavior

The tab item indicator is based on a division of number of tabs evenly

### Screenshots (if applicable)
![Screenshot_20211123-202251_Twitter](https://user-images.githubusercontent.com/46008388/143007636-0760e242-51b9-4a8b-aeca-6a70388c1373.jpg)

**Comment by JaitenThomas** [comment]
Or is it possible to just have a react navigation tab navigator and somehow connect the indicator to the current tabs screen elements?

**Comment by PedroBern** [comment]
The tab width is already dynamically set.

https://user-images.githubusercontent.com/39778068/143154526-77621b76-d4a0-4689-b135-5b9003b93e90.mp4

**Comment by PedroBern** [comment]
@JaitenThomas Feel free to reopen if you mean when sceoll is disabled.
