### ISSUE TITLE
How to Remove MaterialTabBar elevation?

### ISSUE THREAD

**Issue by wel0z** [PedroBern/react-native-collapsible-tab-view#218]
is there a way to remove MaterialTabBar elevation/shadow ? I tried to extend MaterialTabBar with renderTabBar prop but seems not work. Other prop works like a charm

![Schermata 2021-11-24 alle 13 50 02](https://user-images.githubusercontent.com/6516617/143241642-3ee6be94-ad75-4165-8455-e7aaa1ed942b.png)

**Comment by andreialecu** [comment]
See: https://github.com/PedroBern/react-native-collapsible-tab-view/issues/183
