### ISSUE TITLE
how do I use the useHeaderMeasurements hooks

### ISSUE THREAD

**Issue by lzl5771060** [PedroBern/react-native-collapsible-tab-view#219]
When I use useHeaderMeasurements which hooks this error, how do I use it  
example:    const { top, height } = useHeaderMeasurements();
Error:          useTabsContext must be inside a Tabs.Container

**Comment by doolb14** [comment]
Did you find anything? I'm facing the same issue

**Comment by andreialecu** [comment]
Here's an example of how I'm using it.

```tsx
function HeaderScrollPosition({
  onMeasurements,
}: {
  onMeasurements: (measurements: HeaderMeasurements) => unknown;
}) {
  const measurements = useHeaderMeasurements();
  useEffect(() => {
    onMeasurements?.(measurements);
  }, [measurements, onMeasurements]);

  return null;
}

function MyComponent() {
  const [headerMeasurements, setHeaderMeasurements] =
    useState<HeaderMeasurements>();
  const {setOptions} = useNavigation();

  const renderHeader = useCallback(
    () => (
      <View
        pointerEvents="box-none"
        style={...}
      >
        <HeaderScrollPosition
          onMeasurements={(newMeasurements) => {
            // keep previous measurements if we already have some
            setHeaderMeasurements(
              (prevMeasurements) => prevMeasurements || newMeasurements,
            );
          }}
        />
        <Something />
      </View>
    ),
    [...],
  );

  const AnimatedLogo = useCallback(
    () => (
      <MyLogo
        headerMeasurements={headerMeasurements}
      />
    ),
    [headerMeasurements],
  );

  setOptions({headerTitle: AnimatedLogo});

}
```

Achieves an effect like:

https://user-images.githubusercontent.com/697707/149621148-85cf0bb3-01e1-4249-b781-26356692cc56.mp4

**Comment by phuocantd** [comment]
> Here's an example of how I'm using it.
> 
> ```tsx
> function HeaderScrollPosition({
>   onMeasurements,
> }: {
>   onMeasurements: (measurements: HeaderMeasurements) => unknown;
> }) {
>   const measurements = useHeaderMeasurements();
>   useEffect(() => {
>     onMeasurements?.(measurements);
>   }, [measurements, onMeasurements]);
> 
>   return null;
> }
> 
> function MyComponent() {
>   const [headerMeasurements, setHeaderMeasurements] =
>     useState<HeaderMeasurements>();
>   const {setOptions} = useNavigation();
> 
>   const renderHeader = useCallback(
>     () => (
>       <View
>         pointerEvents="box-none"
>         style={...}
>       >
>         <HeaderScrollPosition
>           onMeasurements={(newMeasurements) => {
>             // keep previous measurements if we already have some
>             setHeaderMeasurements(
>               (prevMeasurements) => prevMeasurements || newMeasurements,
>             );
>           }}
>         />
>         <Something />
>       </View>
>     ),
>     [...],
>   );
> 
>   const AnimatedLogo = useCallback(
>     () => (
>       <MyLogo
>         headerMeasurements={headerMeasurements}
>       />
>     ),
>     [headerMeasurements],
>   );
> 
>   setOptions({headerTitle: AnimatedLogo});
> 
> }
> ```
> 
> Achieves an effect like:
> 
>  Simulator.Screen.Recording.-.iPhone.12.-.2022-01-15.at.14.06.53.mp4

Can you share full example?

**Comment by deleonjuan** [comment]
Sorry, what's exactly the soluition for `Error: useTabsContext must be inside a Tabs.Container` ?? looks like all the hooks trigger this error

**Comment by alextbogdanov** [comment]
I'm having the same issue!
