### ISSUE TITLE
useTabsContext must be inside a Tabs.Container

### ISSUE THREAD

**Issue by doolb14** [PedroBern/react-native-collapsible-tab-view#225]
Hi, when I'm trying to use "useAnimatedStyle" hook in js, I'm getting "_useTabsContext must be inside a Tabs.Container_" error. I tried following this [example](https://github.com/PedroBern/react-native-collapsible-tab-view/blob/main/example/src/AnimatedHeader.tsx) but still couldn't make it work

**Comment by andreialecu** [comment]
This might help: https://github.com/PedroBern/react-native-collapsible-tab-view/issues/219#issuecomment-1013671098

**Comment by deleonjuan** [comment]
> This might help: [#219 (comment)](https://github.com/PedroBern/react-native-collapsible-tab-view/issues/219#issuecomment-1013671098)

This is not helpfull at all, What's the root cause of `useTabsContext must be inside a Tabs.Container` issue? and what's exactly the solution???

**Comment by alextbogdanov** [comment]
Same issue here!
