### ISSUE TITLE
How to let the header scrollable and respond to click

### ISSUE THREAD

**Issue by mouxuefei** [PedroBern/react-native-collapsible-tab-view#226]

**Comment by nghaosiong98** [comment]
https://github.com/PedroBern/react-native-collapsible-tab-view#scroll-on-header
Have you try this?

**Comment by nihilenz** [comment]
> https://github.com/PedroBern/react-native-collapsible-tab-view#scroll-on-header
> Have you try this?

You can make the header partially scrollable, but if you need one or more touchables (for example see the Instagram profile screen), they only respond to press touches and prevent the header from scrolling.
Unlike native apps or other projects (i.e. https://github.com/netguru/sticky-parallax-header), it seems touchables are not scrollable and vice versa. Or am I wrong?
