### ISSUE TITLE
Scroll offset doesn't sync for each route using multiple ScrollViews

### ISSUE THREAD

**Issue by favorxo** [PedroBern/react-native-collapsible-tab-view#241]
https://user-images.githubusercontent.com/47069365/155219321-bad79038-a1a0-4d49-8e3b-c25110394a14.mp4

**Comment by littletreezlx** [comment]
same problem

**Comment by xapss** [comment]
same problem here.

**Comment by andreialecu** [comment]
I believe this is the same as https://github.com/PedroBern/react-native-collapsible-tab-view/issues/221

Which version of Reanimated are you using? Run `yarn why react-native-reanimated` and post the output please.

**Comment by vkochukov** [comment]
Same problem, I'm using 2.4.1

**Comment by vkochukov** [comment]
Same problem. I'm using 2.4.1. I downgraded to 2.2.3 but it didn't help. Works fine if I downgrade [react-native-collapsible-tab-view](https://github.com/PedroBern/react-native-collapsible-tab-view) to 2.3.0

**Comment by vkochukov** [comment]
Same problem. I'm using `2.4.1`. I downgraded to `2.2.3` but it didn't help. Works fine if I downgrade [react-native-collapsible-tab-view](https://github.com/PedroBern/react-native-collapsible-tab-view) to `4.3.0`

**Comment by vkochukov** [comment]
Same problem. I'm using `2.4.1`. I downgraded to `2.2.3` but it didn't help. Works fine if I downgrade [react-native-collapsible-tab-view](https://github.com/PedroBern/react-native-collapsible-tab-view) to `4.2.0`

**Comment by vkochukov** [comment]
Same problem. I'm using 2.4.1. I downgraded to 2.2.3 but it didn't help.
I reverted this commit [commit](https://github.com/PedroBern/react-native-collapsible-tab-view/commit/dd6d2efd97337ce29903650de3d072a32de540db) and route sync started working

**Comment by vkochukov** [comment]
Same problem. I'm using `react-native-reanimated 2.4.1`. I downgraded `react-native-reanimated` to `2.2.3` but it didn't help.
I reverted this commit [commit](https://github.com/PedroBern/react-native-collapsible-tab-view/commit/dd6d2efd97337ce29903650de3d072a32de540db) and scroll offset sync started working for each route

**Comment by andreialecu** [comment]
This is likely to be resolved in v5, try installing it via yarn add react-native-collapsible-tab-view@rc

Let me know if it is still an issue.
