### ISSUE TITLE
Regressions: v5 RC breaks all touchables by react-native-gesture-handler in FlatList

### ISSUE THREAD

**Issue by hirbod** [PedroBern/react-native-collapsible-tab-view#256]
@andreialecu I can tell you that I've upgraded and the first thing I realized is that that new release is breaking the swipe behavior in my view. I can only swipe tabs now when I place my finger on the tabs directly or when I swipe in the header area or on a view that does not use touchables by RNGH. 

It does not play nicely with `RectButton, BaseButton etc` by react-native-gesture-handler anymore. It does work with RN-Touchables (which should not be used in FlatLists anyway, because they don't work nicely with FlatList, activating with scroll which they should not) 

It does work with TouchableOpacity, TouchableWithoutFeedback etc (from react-native) though
v4 did not had any issues with RectButton

P:S: Can't select "issue" as "issue", only Feature Requests and Questions.

**Comment by hirbod** [comment]
It does also break the workaround used here: #248

**Comment by hirbod** [comment]
For now (with a broken heart), I swapped RectButton with TouchableWithoutFeedback.
I really did nothing but upgrading and got those weird TabNameContext issues. Could not reproduce that after upgrade to RC.4 for now - weird (maybe metro bundle cache or some node_modules weirdness again when working with monorepos)

Ok, whats left is RNGH :/

**Comment by andreialecu** [comment]
If you'd like to help out to figure out if there are any workarounds, or the reason for the RNGH issue it would be greatly appreciated.

**Comment by hirbod** [comment]
Are you importing Flatlist from RN or from RNGH? Usually it's enough to use Flatlist by RNGH to get rid of touchable issues (it's also preferred when working with gestures).

**Comment by hirbod** [comment]
Hm... dang. I'm also seeing my items disappear sometimes now, like when you use removeClippedSubviews. It happens very randomly, have to investigate further

**Comment by hirbod** [comment]
I filed an issue at both repos

**Comment by hirbod** [comment]
Just figured that `containerStyle` is also not working with the new RC. Had to make small adjustments

**Comment by hirbod** [comment]
My PR has been merged, it was an issue with pager-view. A new version has been released.

**Comment by anabeatrizzz** [comment]
> Other regressions:
> 
> * useTabsContext must be inside a Tabs.Container.
> * useTabNameContext muss be inside a TabNameContext
> 
> I am not even using this. Its coming from the FlatList Implementation.

I was facing the same issue. The error disappeared after I changed `Tabs.ScrollView` for `Animated.ScrollView`.
