### ISSUE TITLE
Would it be possible to collapse header using a ref?

### ISSUE THREAD

**Issue by sayran123** [PedroBern/react-native-collapsible-tab-view#266]
Hi, I have a specific tab where i don't want to have the renderHeader showing and I was wondering if it would be possible to collapse the header using a ref. 

Currently I am using a state variable to decide if the header should render but thats a little buggy. I was hoping that there would be a way for me to scroll the header up kind of like scrollview's scrollTo() Method. 

`renderHeader={() => showHeader ? headerRender() : null}`

I tried wrapping the headerRender component in a scrollview and tried a scrollTo but that didn't work for obvious reasons. 

Any help would be appreciated

**Comment by andreialecu** [comment]
You should be able to use `scrollTo` on the `ref`, something like:

```ts
  const headerMeasurements = useHeaderMeasurements();
  
  ...
  scrollView.current?.scrollTo({ x: 0, y: headerMeasurements.height.value, animated: true })
```

**Comment by sayran123** [comment]
Ok I think I didn't effectively phrase my question. Currently, the header that I am rendering is a view with a fixed size (not a scrollview). 

I am currently assuming that the tabs.container is a ScrollView as it allows the user to scroll through a header to the body of the tabs. I was wondering if my assumption is correct and, if it is, how do i gain access to the props and methods of that scrollview? 

I currently have the ref like this:
`<Tabs.Container  
      ref={tabContainerRef} 
      ...props 
  />`

I have tried:
`tabContainerRef.current?.scrollTo({ x: 0, y: headerMeasurements.height.value, animated: true })`
which is currently returning me an error saying that it is not a function.

Is it possible to use a ref in this location to scroll the header closed? Is there another location that I should try? 

Thanks for the help!

**Comment by andreialecu** [comment]
`Tabs.Container` is not a scrollview so you will not be able to scroll it. The inner tabs are scrollviews.

I see in your initial post that you mentioned `renderHeader={() => showHeader ? headerRender() : null}`. That should work, what is the problem with it?

**Comment by sayran123** [comment]
If I were to scroll up the header and then nav to the tab that I don't want to render the header that works fine. However when I go back to a tab that shows the header it flashes the unscrolled header before showing its true scrolled up state. The flash of that unscrolled header makes it look like a bug. Its not the biggest deal but if you have a solution that would be appreciated
