### ISSUE TITLE
How would I use this with Shopify's new Flashlist?

### ISSUE THREAD

**Issue by ansh** [PedroBern/react-native-collapsible-tab-view#273]
Instead of `Tabs.FlatList` I want to use @Shopify 's new [FlashList package](https://github.com/Shopify/flash-list).

How would I replace `Tabs.FlatList` with `FlashList`?

**Comment by ansh** [comment]
@shopify

**Comment by baronha** [comment]
same +1

**Comment by AtakanAksal** [comment]
same +1

**Comment by ansh** [comment]
@efstathiosntonas It's really funny you mentioned that because @bonfim996 was working with me and he created that fork to solve exactly this issue!

I recommend that fork as well.

**Comment by andreialecu** [comment]
FlashList support is available in version 6.1.0
