### ISSUE TITLE
Respond to scroll gestures on collapsible header

### ISSUE THREAD

**Issue by yfunk** [PedroBern/react-native-collapsible-tab-view#28]
### Feature request
In some cases, where the collapsible header covers a significant amount of the vertical screen space, a user might prefer or even be forced to start their scroll gesture on the collapsible header. There are a few cases I can think of where this may happen:

- **When the header is used to display larger amounts of content**. Say you are developing a delivery app and want to display some pictures and information about a restaurant above a tab list of all their dishes. The header will initially cover most of the screen (see Illustration).
- **When using a small screen device**. While phones with small screens admittedly seem to be a dying breed a bunch of them are still out there. Due to different scaling and aspect ratios most headers would likely cover >50% of the screen.
- **When using split screen mode on Android devices**. Even regular sized collapsible headers like in the example app will cover almost all of the available window height (see Screenshot).

Currently, when starting a scroll gesture on the header nothing happens at all. It would be nice if there was a (opt-in) way for these gestures to be passed or translated to the `ScrollView` / `FlatList` inside the focused tab. This behavior would also be consistent with some native implementations collapsible headers (e.g the "Galaxy Store" App).

If anyone has ideas on how this could be implemented I would love to help and open a PR.

### Screenshots
| Large header  | Android Split Screen |
| ------------- | ------------- |
| ![Header with large amounts of content](https://user-images.githubusercontent.com/14955991/103179233-0c101780-488a-11eb-895b-1876bc1db46e.png)  | ![split_screen](https://user-images.githubusercontent.com/14955991/103180151-5e096b00-4893-11eb-9fe9-5f3ee59a709a.png)|

**Comment by PedroBern** [comment]
Hi @yfunk I already opened a PR to fix it, but it's not ready yet. You can help by reviewing it :)

**Comment by PedroBern** [comment]
Check out the expo preview app for #30 .

[expo.io/@pedrobern/react-native-collapsible-tab-view-demos?release-channel=pr-30](https://expo.io/@pedrobern/react-native-collapsible-tab-view-demos?release-channel=pr-30)

<a href="https://expo.io/@pedrobern/react-native-collapsible-tab-view-demos?release-channel=pr-30"><img src="https://api.qrserver.com/v1/create-qr-code/?size=400x400&data=exp://exp.host/@pedrobern/react-native-collapsible-tab-view-demos?release-channel=pr-30" height="200px" width="200px"></a>

@andreialecu maybe it's an important feature for you. If you have time I appreciate some help (as always).

The PR has a bug, reproduce following these steps (easier to see on the **Without snapping** example): 
- scroll with the fingers on the header
- release
- scroll with the fingers on the header again
- at this point, you can see the bug.
