### ISSUE TITLE
onScroll and some other props of FlatList are not available

### ISSUE THREAD

**Issue by linweiboy** [PedroBern/react-native-collapsible-tab-view#281]
I need to monitor the value of scrollY in real time and then implement some functions, but the onScroll method is invalid.
I need your help, thanks

**Comment by LinceMathew** [comment]
its showing an error undefined is not an object(evaluating tabNames.value.indexOf) in line number 179 ,hooks.tsx

**Comment by linweiboy** [comment]
> 

Thanks.But I found a new problem, the head does not slide along with the iOS real device test, the whole head and the tab bar are suspended together to the top

**Comment by nica0012** [comment]
Any update on using onScroll in a class component? I too need to track the scroll Y value of the tabs.flastlist
