### ISSUE TITLE
how to import `useCurrentTabScrollY`

### ISSUE THREAD

**Issue by phuocantd** [PedroBern/react-native-collapsible-tab-view#295]
I want to use `useCurrentTabScrollY` like Animated Helper example but I cannot import this

Environment
    "react": "18.1.0",
    "react-native": "0.69.4",
    "react-native-collapsible-tab-view": "^0.70.1",

**Comment by phuocantd** [comment]
https://github.com/PedroBern/react-native-collapsible-tab-view/blob/main/example/src/AnimatedHeader.tsx

**Comment by Bimbimz** [comment]
same problem
import { useCurrentTabScrollY } from '../../src/hooks'
is nothing what your mean?

**Comment by phuocantd** [comment]
when I use `useTabsContext` then error: useTabsContext must be inside a Tabs.Container

![image](https://user-images.githubusercontent.com/31690470/193501596-bc118fab-1978-45cb-8aab-ab80713d8448.png)

**Comment by nica0012** [comment]
How did you get this imported? Am I missing something?

**Comment by alextbogdanov** [comment]
I'm having the same issue

**Comment by fistofzen** [comment]
any solution?
