### ISSUE TITLE
Bug when using lazy mode with react-native-collapsible-tab-view version 5.0.0-rc.13

### ISSUE THREAD

**Issue by timothygorer** [PedroBern/react-native-collapsible-tab-view#308]
I am trying to use the lazy property when declaring <Tabs.Container lazy ...></Tabs.Container>. Only the first tab is rendering, and all other tabs are completely blank. The issue goes away when I remove "lazy". I am using a Tabs.FlatList in each of the tabs. The lazy property worked when I was on version 4.5.2 of the react-native-collapsible-tab-view. Would appreciate any help in resolving this matter.

**Comment by timothygorer** [comment]
@PedroBern is this a known issue?

**Comment by timothygorer** [comment]
bump, anyone?

**Comment by timothygorer** [comment]
@alexpchin @andreialecu is this a known issue?

**Comment by premhowli-buyhatke** [comment]
using 6.1.4 version of app. We are seeing that if we use lazy, sometimes it does not load the component of a particular tab infinitely, and navigating through routes also could cure sometimes only.

**Comment by FabianDean** [comment]
I get something like this occasionally on the second tab only of many tabs.

Swiping to it from the first shows nothing, but going to the third tab (which renders) then coming back to the second seems to resolve it.

Any developments on this issue?
