### ISSUE TITLE
Reanimated 3.0 support

### ISSUE THREAD

**Issue by BooYeu** [PedroBern/react-native-collapsible-tab-view#321]
react-native-reanimated@3.0.1
It shows error:
Error: runOnUI() can only be used on worklets, js engine: hermes

**Comment by andreialecu** [comment]
Try version 6.0.0-rc.0

Fixed in #322

**Comment by BooYeu** [comment]
> Try version 6.0.0-rc.0
> 
> Fixed in #322

Thank you for the reply ! But I didn't find a released package in npm, When will it become released ?

**Comment by andreialecu** [comment]
It's released as a release candidate under that tag: https://www.npmjs.com/package/react-native-collapsible-tab-view?activeTab=versions

**Comment by BooYeu** [comment]
I got it! Thank you very much!





------------------ Original ------------------
From: Andrei Alecu ***@***.***&gt;
Date: Sat,Mar 4,2023 10:45 PM
To: PedroBern/react-native-collapsible-tab-view ***@***.***&gt;
Cc: 刘力瑞 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [PedroBern/react-native-collapsible-tab-view] Error: runOnUI() can only be used on worklets, js engine: hermes (Issue #321)





 
It's released as a release candidate under that tag: https://www.npmjs.com/package/react-native-collapsible-tab-view?activeTab=versions

**Comment by andreialecu** [comment]
Just released version 6.0.0 as a major. It fixes another issue I recently found. Please update to the latest and let me know if you find any issues.

**Comment by andreialecu** [comment]
Note that I noticed an issue with Reanimated 3.0, for which I opened an upstream report here: https://github.com/software-mansion/react-native-reanimated/issues/4168

**Comment by BooYeu** [comment]
I tried 6.0.1 just now, but it seems like something wrong in second tab:

https://user-images.githubusercontent.com/16587763/222939339-7613c3d3-f822-4b6f-8627-a3134d1c6592.mp4

And My codes below:
`
<Tabs.Container
      renderHeader={renderHeader}
      renderTabBar={renderTabBar}
      headerContainerStyle={byStyle.transparent}>
      <Tabs.Tab name="image">
        <PositionOneImage pcode={route.params.id} />
      </Tabs.Tab>
      <Tabs.Tab name="comment">
        <PositionOneComment pcode={route.params.id} />
      </Tabs.Tab>
    </Tabs.Container>

const PositionOneImage = (
  <Tab.Flatlist />
)

`

**Comment by BooYeu** [comment]
I found that it will happen when the Tab.FlatList data doesn't fill all the screen.
Change the example file:https://github.com/PedroBern/react-native-collapsible-tab-view/blob/main/example/src/Shared/QuickStartDemo.tsx 
from const DATA = [0, 1, 2, 3, 4]  to const DATA = [0] can show this problem

**Comment by andreialecu** [comment]
Version 6.1.1 supports the latest reanimated.
