### ISSUE TITLE
Is there some simple guide to using this library?

### ISSUE THREAD

**Issue by bpeck81** [PedroBern/react-native-collapsible-tab-view#330]
I don't have any experience with Reanimated, though it seems that it's a requirement to use this library. I'm trying to do some simple things, like change the text size in the tabs, but the code looks pretty intricate to just make a small change. Is there a simple guide to using this?

**Comment by bpeck81** [comment]
<img width="540" alt="Screenshot 2023-04-12 at 3 11 20 PM" src="https://user-images.githubusercontent.com/7690994/231560650-077a82d6-976c-4933-9603-73e05f787352.png">

I did run yarn install and npm install.

**Comment by bpeck81** [comment]
I appreciate your work, but wouldn't it be better to make an easy to use guide as part of your documentation...? Or do you really want people to comb through your example code?

**Comment by bpeck81** [comment]
I am unable to setup your example app locally.
<img width="298" alt="Screenshot 2023-04-12 at 3 17 42 PM" src="https://user-images.githubusercontent.com/7690994/231562044-b2d88661-dc0f-4325-9db8-3a29c03d86e3.png">

**Comment by andreialecu** [comment]
> I appreciate your work, but wouldn't it be better to make an easy to use guide as part of your documentation...? Or do you really want people to comb through your example code?

Please feel free to improve this, PRs appreciated. 🙏 

> I am unable to setup your example app locally.

You cannot use Expo Go, you'll need to create a native development build. Try `yarn ios` or `yarn android` in the `example` directory.

**Comment by bpeck81** [comment]
<img width="893" alt="Screenshot 2023-04-12 at 3 57 09 PM" src="https://user-images.githubusercontent.com/7690994/231570612-433c5eab-c7c2-4935-8276-88174304a47f.png">

I am reaching this error.

**Comment by bpeck81** [comment]
https://user-images.githubusercontent.com/7690994/232101959-16a620b1-2532-4400-97cd-a5396ad6aaf8.mov

This is the problem I am having. Do you think you can help? It works properly when I surround the tabs container with a scrollview. I can provide code if that helps.

**Comment by bpeck81** [comment]
Okay I played around with this library for a while and it turns out it was not user error, but the library has issues. I'll share what worked for me to save others time.
1. The library example doesn't work because the author hasn't updated it to the latest SDK. 
2. The View that come before the collapsible header needs to have style={{zIndex:0, backgroundColor:'MyColor'}}
3. You may need to experiment with background colors and set them explicitly rather than leaving them as default transparent..
4. The animated header example isn't useful. What worked for me was structuring  my header component like this: <View><Animated.View>{your header content}</Animated.View></View>
5. Your header isn't supposed to have touchable opacities in it. If it does, you'll have to deal with pointer events.
6. You can't scroll the header and have touchables in it. That's a big problem for most people!

But... I found an obscure comment [here](https://github.com/PedroBern/react-native-collapsible-tab-view/issues/144) and it turns out I don't even need to use this library at all (no offense to the creator, but I recommend people who read this don't. It has a lot of issues and is unnecessarily complex). It works perfectly, with a scrollable header and touchables in the header!

If you use a specific version of react native tab view you can literally just use a scrollview with your header. It will not work with the current version.

Use this:
`yarn add react-native-tab-view@2.16.0 `



My code ended up looking super simple:
```
import { TabBar, TabView } from 'react-native-tab-view'

const MyComponent = ()=>{

const [index, setIndex] = useState(0)
return(
<View style={{ flex: 1 }}>
<MyPermanentTopHeader />
<ScrollView>
    <MyCollapsibleHeader />
    <TabView
        navigationState={{ index, routes: [{ key: 'tab1', title: 'tab2' }, { key: 'tab1', title: 'tab2' }] }}
        renderScene={({ route }) => {
            switch (route.key) {
                case 'tab1':
                    return <FlatList (with all my data) />
                case 'tab2':
                    return <FlatList (with all my data ) />
                default:
                    return null;
            }
        }}
        onIndexChange={setIndex}
        renderTabBar={props => <TabBar
            {...props}
            renderLabel={({ route }) => (
                <Text style={{MyStyling}}>
                    {route.title}
                </Text>
            )}
            indicatorStyle={{ backgroundColor: 'blue' }}
            style={{ backgroundColor: 'white' }}
        />}
    />
</ScrollView>
</View>
)
```

**Comment by bpeck81** [comment]
@PedroBern  I tried [this](https://github.com/zyslife/react-native-head-tab-view) library but like yours better. I can generally make yours work but the main feature yours is missing which this has is that you can press items in the collapsible header. Is there any way you would be willing to implement that feature? What would it take for you to do that?

**Comment by andreialecu** [comment]
You can press items in the header. There's an example that shows that. It's not perfect, however and has some limitations. It has been discussed several times in the issues in this repository.

Implementing it properly is currently not possible due to upstream limitations. See: https://github.com/software-mansion/react-native-gesture-handler/discussions/2033#discussioncomment-2747981

**Comment by bpeck81** [comment]
My fault, I meant be able to press buttons and scroll on the header. My app has a very large header, so it requires scrolling unfortunately. I've been stuck on this problem for almost a week. Modifying pointerEvents doesn't seem to work well, so I can't scroll unless I change my header pointerEvents 'none'. 

So there's no way to fix this? 
For what it's worth, I can scroll over a header and switch tabs with the code I shared above, but there are issues with it: the tabbar doesn't stick to the top, swiping to switch views causes the list swiped from to be pressed, and the list lengths are not changed when you switch views.

**Comment by bpeck81** [comment]
Adding on to my example above, I've found a way to give it all required functionality except swiping between screens. So it's a tradeoff to have a scrollable and pressable collapsible header instead of swiping between screens, which is a tradeoff I need to make for my app. As a side effect, I notice that this method also has the screens better adapt to the size of the lists in each page and better image scrolling performance.

```
const [index, setIndex] = useState(0)
return(
<View style={{ flex: 1 }}>
<MyPermanentTopHeader />
<ScrollView
          showsVerticalScrollIndicator={false}
          stickyHeaderIndices={[1]}
>
    <MyCollapsibleHeader />
    <TabView
        navigationState={{ index, routes: [{ key: 'tab1', title: 'tab2' }, { key: 'tab1', title: 'tab2' }] }}
        renderScene={({ route }) => {
            switch (route.key) {
                case 'tab1':
                           break;
                case 'tab2':
                           break;
                default:
                    return null;
            }
        }}
        onIndexChange={setIndex}
        renderTabBar={props => <TabBar
            {...props}
            renderLabel={({ route }) => (
                <Text style={{MyStyling}}>
                    {route.title}
                </Text>
            )}
            indicatorStyle={{ backgroundColor: 'blue' }}
            style={{ backgroundColor: 'white' }}
        />}
    />
      {index == 0 ? (
                <FlatList .... />
      ) : (
                <FlatList .... />
      )}
</ScrollView>
</View>
)
```

**Comment by senghuotlay** [comment]
@bpeck81 for some reason why i follow your solution, i am unable to scrolldown to my flatlist :(

**Comment by coofzilla** [comment]
> I appreciate your work, but wouldn't it be better to make an easy to use guide as part of your documentation...? Or do you really want people to comb through your example code?

I had a similar issue; however, after just cloning and building it, the example app is actually awesome. Its not _as_ convenient as typical documentation; but, its really really good.
