### ISSUE TITLE
Are there any plans to integrate the Masonry layout from Flashlist?

### ISSUE THREAD

**Issue by HaiPe1973** [PedroBern/react-native-collapsible-tab-view#339]
Hi guys,
first of all thank you for this great tool! This component has been missing in react native!
Also great news was that Flashlist will be integrated.

My question is already in the title:
After Flashlist is incorporated, is it planned to provide also the Masonry layout of Flashlist in your component? And if so, when will it be built in?

**Comment by andreialecu** [comment]
PR is welcome. It should be relatively straightforward.

If you'd like to give it a try take a look at: https://github.com/PedroBern/react-native-collapsible-tab-view/pull/332

**Comment by HaiPe1973** [comment]
Hello, in the next 2, 3 weeks I have too much to do at work, but then I will be happy to give them a try.

**Comment by gkartalis** [comment]
I think this can be closed. Adressed in the prs below
- https://github.com/PedroBern/react-native-collapsible-tab-view/pull/353
- https://github.com/PedroBern/react-native-collapsible-tab-view/pull/360

**Comment by HaiPe1973** [comment]
Great work, thank you!
