### ISSUE TITLE
Unable to resolve "../Utilities/Platform" w/ Metro bundler

### ISSUE THREAD

**Issue by devoren** [PedroBern/react-native-collapsible-tab-view#345]
Hey! Love this library ❤️. I have a problem with the lib when I use it in expo web where Metro is used as the bundler. I need to use metro because of expo router. Do you know how to solve the problem?

<img width="608" alt="image" src="https://github.com/PedroBern/react-native-collapsible-tab-view/assets/99968085/b62a0df3-829f-4a24-a737-7f88aebca219">

**Comment by andreialecu** [comment]
Could you clarify why you believe that error is related to this library?

**Comment by devoren** [comment]
@andreialecu When I remove the react-native-collapsible-tab-view import the error disappears

**Comment by devoren** [comment]
I downloaded example and tried to run it:

<img width="878" alt="image" src="https://github.com/PedroBern/react-native-collapsible-tab-view/assets/99968085/1a95a274-17a1-423b-8f5b-bb817107a741">

**Comment by devoren** [comment]
On the "native" works without any problem

**Comment by andreialecu** [comment]
Take a look through https://github.com/expo/expo/issues/16227 and related issues. I think it's an Expo issue of some sort.

**Comment by devoren** [comment]
Yes, I checked them all, but so far none of the solutions work :(

**Comment by devoren** [comment]
@andreialecu is it posibble to import file only if platform is mobile or native?
I tried something like this: 
```
var CollapsibleTabs =
	Platform.OS !== 'web' ? require('src/components/Home/Tabs/CollapsibleTabs') : null;
```

**Comment by andreialecu** [comment]
See the sections at the end of: https://reactnative.dev/docs/platform-specific-code

**Comment by devoren** [comment]
@andreialecu It helps, for now in "web" I use rn tab-view, but i hope the problem will be solved soon

**Comment by Jonatthu** [comment]
@sayem314 @devoren @andreialecu This is happening to me as well on web bundling and looks like it's due this library is accessing to private libraries from react native, https://github.com/callstack/react-native-pager-view/blob/master/src/PagerViewNativeComponent.ts

A solution could be to replace this just like react navigation did on web:

https://github.com/react-navigation/react-navigation/blob/main/packages/react-native-tab-view/src/Pager.tsx

**Comment by Jonatthu** [comment]
@andreialecu https://snack.expo.dev/@satya164/react-native-tab-view-custom-tabbar
Please consider this web rendered version of a tabview

**Comment by martinezguillaume** [comment]
that's a complicated question,
or we create a PagerView web compatible (copy from rn tab-view)
or directly using the whole rn tab-view only on web side

For me, as rn tab-view did, using a PagerView adapter only for web would be a good solution
I think the purpose of this repo is to not use rn tab-view

**Comment by saulamsal** [comment]
Any update on this? Looking at the code, all we need is replace PagerView like rn tab-view does.

**Comment by oksana-vyshinskaya** [comment]
In my case it helped
```
alias: {
  'react-native$': require.resolve('react-native-web'),
}
```
[RN Paper web support guide](https://callstack.github.io/react-native-paper/docs/guides/react-native-web/#1-alias-react-native-to-react-native-web)

**Comment by Jonatthu** [comment]
@oksana-vyshinskaya, what do you mean? did you make it work on the web?

**Comment by Jonatthu** [comment]
I made it work on the web *Chef kiss*

https://github.com/user-attachments/assets/a847595b-19f4-4110-916d-4703a7255ee3

**Comment by miguelpveloso** [comment]
@Jonatthu how did you do it? Could you share some insights?

I'm having the `Error: Importing native-only module "react-native/Libraries/Utilities/codegenNativeCommands" on web from: ..../node_modules/react-native-pager-view/lib/module/specs/PagerViewNativeComponent.js`

**Comment by Jonatthu** [comment]
I forked the library and modified the code, I wonder if @andreialecu would accept a PR, I am not sure because that would mean for him another platform to support which is web.

**Comment by ollyde** [comment]
I also have this issue but no idea what library is causing it, maybe more debug information would be good here.

**Comment by miguelpveloso** [comment]
@Jonatthu could you point me to the branch/commit that contains the change you've made?

**Comment by miguelpveloso** [comment]
I'd appreciate if you could show the Adapter you have.
