### ISSUE TITLE
Scroll gets reset for header when switching between tabs via click or swipe

### ISSUE THREAD

**Issue by premhowli-buyhatke** [PedroBern/react-native-collapsible-tab-view#348]
The scroll percentage of the header gets reset when switching tabs via a click or swipe.
A screen recording of the issue follows.

https://github.com/PedroBern/react-native-collapsible-tab-view/assets/126082718/69d7bca7-240b-4fc2-ad23-43f8a0747e4d

**Comment by vxm5091** [comment]
@premhowli-buyhatke how did you end up fixing this?

**Comment by francoangulo** [comment]
@premhowli-buyhatke did you find a solution for this? how?
