### ISSUE TITLE
Is it possible to reveal header on tab change? 

### ISSUE THREAD

**Issue by ryanSoftwareEngineer** [PedroBern/react-native-collapsible-tab-view#380]
On tab change if the tab has less items than can fit the screen, I want to scroll to the top, revel the header and disable scrolling. 
Currently if I change tab and there is only a single item in my list, I can still scroll down and hide the header showing a blank screen. If not i'll probably just adjust the size of the elements when there's few.

**Comment by VictorioMolina** [comment]
@ryanSoftwareEngineer did you find a solution?
