### ISSUE TITLE
Header is reseting when switching to 5th tab from 1st tab

### ISSUE THREAD

**Issue by rifad4u** [PedroBern/react-native-collapsible-tab-view#388]
Package is failing to keep the header when switching between 1st to tab to 5th tab.
Please check the attached video for better understanding.

[Tab switch issue.webm](https://github.com/PedroBern/react-native-collapsible-tab-view/assets/37132763/d5be7bee-cd1d-4e7b-ae42-079c732b7ec7)

**Comment by suryapermana92work** [comment]
same issue

**Comment by andreialecu** [comment]
https://github.com/PedroBern/react-native-collapsible-tab-view/pull/394 might fix this, I released it as 7.0.1-beta.0 on npm. Please help test it for unwanted side effects and report back. Thanks!

**Comment by suryapermana92work** [comment]
> #394 might fix this, I released it as 7.0.1-beta.0 on npm. Please help test it for unwanted side effects and report back. Thanks!

https://github.com/PedroBern/react-native-collapsible-tab-view/assets/62427933/20f436da-88d1-48a5-9f7b-e43eed89c1c2

i think it's solved but on Tabs.FlashList still reseting @andreialecu

**Comment by andreialecu** [comment]
I notice that you have something weird going on with the size of your flashlist for a split second. This doesn't look normal and I don't think it's related to this library:

![CleanShot 2024-04-19 at 08 59 44@2x](https://github.com/PedroBern/react-native-collapsible-tab-view/assets/697707/aa1d7d08-dbf1-4db6-830d-5b211babe8ec)

A repro would help. It could be related to #335 but it's hard to tell. If you can repro it, please open a new issue.

Will close this for now.
