### ISSUE TITLE
change the indicator style

### ISSUE THREAD

**Issue by 111Tashmo** [PedroBern/react-native-collapsible-tab-view#390]
I want to selfstyle the indicator, no dynamically, like this. but I cant see any props about the indicatorStyle, any solutions? 
<img width="198" alt="截屏2024-03-10 11 34 55" src="https://github.com/PedroBern/react-native-collapsible-tab-view/assets/112067237/02cf68e1-21e5-4b6e-93bd-6fda628a0e03">
in react-native-tab-view they have the styleprops about the indicator, I wonder if this library can do so.
<img width="1000" alt="截屏2024-03-10 11 37 16" src="https://github.com/PedroBern/react-native-collapsible-tab-view/assets/112067237/366678d2-15ec-49ae-a192-cbc174c3ae9a">

**Comment by PratikAwaik** [comment]
+1

**Comment by Fardeen-N** [comment]
+1

**Comment by dmnkhvl** [comment]
You can style it using indicatorStyle property on MaterialTabBar. But the problem is setting a width, because the Indicator component set's that every time it moves.

f.e.
`
<Tabs.MaterialTabBar
              indicatorStyle={{
                backgroundColor: '#0F0D66',
                height: 4,
                borderTopLeftRadius: 6,
                borderTopRightRadius: 6,
              }}
            />
`

**Comment by andreialecu** [comment]
I'm not sure I understand this issue, but #395 made some changes here. Styling the indicator should be possible in several ways, please see the Example app in the repository.

**Comment by mr-linge** [comment]
This is ineffective. Is there any method or case that can be set up
