### ISSUE TITLE
VirtualizedList missing

### ISSUE THREAD

**Issue by adrianurs** [PedroBern/react-native-collapsible-tab-view#396]
### Feature request

During the use of react-native-collapsible-tabs I noticed that there is no possibility of virtualization, that creates an incredible delay during render of complex items. As per rn docs 'Virtualization massively improves memory consumption and performance of large lists' which would be awesome if you want to render a complex item.

### Current behavior

Currently is available only FlatList, which is fine for simple items

**Comment by andreialecu** [comment]
[FlatList is implemented using VirtualizedList. ](https://reactnative.dev/docs/virtualizedlist)

If you need more performance you can use FlashList which is also supported by this library.
