### ISSUE TITLE
RefreshControl wrong position on iOS

### ISSUE THREAD

**Issue by aminerol** [PedroBern/react-native-collapsible-tab-view#4]
The RefreshControl be shown on top of the header where it should be shown at top of FlatList itself, is there any workaround so the RefreshControl stick at the top of FlatList

**Comment by PedroBern** [comment]
Hi @aminerol I've just added this in the [example](https://github.com/PedroBern/react-native-collapsible-tab-view/commit/eba4cab8d9d975a6571bb495892e3d4eddd85787). The [new expo app](https://expo.io/@pedrobern/projects/react-native-collapsible-tab-view-demos) is already published with the changes. Check out the `contacts` tab. Although it's an android implementation, we still need an ios workaround.

**Comment by kiwina** [comment]
Hi, i tried setting progressViewOffset on android to have the control on top of the page, and its there problem is its behind the header, don't see a way to change the zindex of it. Any solutions?

**Comment by PedroBern** [comment]
@kiwina can you share the code?

**Comment by alexpchin** [comment]
@PedroBern Is this still relevant? Is @aminerol asking for the `RefreshControl` to be shown below the header?

**Comment by alexpchin** [comment]
Are we talking about implementing:

- https://reactnative.dev/docs/scrollview#contentinset (iOS)
- https://reactnative.dev/docs/scrollview#contentoffset (iOS)

Because:

- https://reactnative.dev/docs/flatlist#progressviewoffset (Android)

Just trying to understand what @aminerol is asking for?

**Comment by PedroBern** [comment]
@alexpchin I will check this later, there is a [related question on StackOverflow](https://stackoverflow.com/questions/56969502/progressviewoffset-for-ios-refresh-control-react-native) that may help to solve this.

**Comment by PedroBern** [comment]
> Is this still relevant? 

I don't think so, I will close this now
