### ISSUE TITLE
Headers are not collapsed when using Tabs.FlashList.

### ISSUE THREAD

**Issue by Ucekay** [PedroBern/react-native-collapsible-tab-view#400]
(Written with machine translation)
### Description
When using Tabs.FlashList (and Tabs.MasonryFlashList), the header does not change in any way and does not fold; with Tabs.FlatList and Tabs.ScrollView it works fine and the header folds.
In addition, when moving to Tabs.FlashList with the header collapsed in Tabs.FlatList, etc., the height of the Header is maintained, but if the FlashList is scrolled down, a blank space equal to the height of the Header is created.

### Steps to reproduce
Fork this repository and run the example app

### Video

https://github.com/PedroBern/react-native-collapsible-tab-view/assets/122760705/ef879d51-8b19-4ea3-823a-dd8d6db42a24

**Comment by NickKotte** [comment]
same here

**Comment by tomas1808** [comment]
Same!

**Comment by vbylen** [comment]
can confirm

**Comment by YahyaBagia** [comment]
+1 same issue

**Comment by NickKotte** [comment]
same. worked before i updated expo and maybe accidently updated this package

**Comment by tomas1808** [comment]
Fixed this by setting react-native-reanimated to exactly "3.8.1" 👍

**Comment by vbylen** [comment]
@tomas1808 interesting, I tried this but didn't work. Is this version 7.0.1 of `react-native-collapsible-tab-view`?

**Comment by tomas1808** [comment]
@vbylen My exact configuration is:

- `"react-native-collapsible-tab-view": "^7.0.1"`
- `"react-native-pager-view": "^6.2.3"`
- `"react-native-reanimated": "3.8.1"`

**Comment by saulamsal** [comment]
@tomas1808 what about `react-native-gesture-handler`?

**Comment by tomas1808** [comment]
@saulamsal `"react-native-gesture-handler": "~2.14.0"`

**Comment by Ucekay** [comment]
> Fixed this by setting `react-native-reanimated` to exactly `3.8.1` 👍

Thank you, @tomas1808 !
I am able to solve this by simply changing `reaxt-native-reanimated` to `3.8.1`. Here are the versions of the packages.

- `"react-native-collapsible-tab-view": "^7.0.1"`
- `"react-native-pager-view": "^6.3.0"`
- `"react-native-gesture-handler": "^2.16.0"`

I have a feeling that this problem is related to [this issue](https://github.com/software-mansion/react-native-reanimated/issues/5941#issuecomment-2085785963) that has been occurring since version `3.9.0` of `react-native-reanimated`.

**Comment by tomas1808** [comment]
@Ucekay Glad it worked for you! Not sure why not everyone is having the same success. 

I'll use this moment to promote my [own question ](https://github.com/PedroBern/react-native-collapsible-tab-view/issues/404) 😆

**Comment by YahyaBagia** [comment]
This package used to work seamlessly with `expo`. However, after upgrading from `expo` SDK 50 to SDK 51, the following dependencies were updated:

- `react-native-reanimated`: `~3.6.2` → `3.10.0`
- `react-native-pager-view`: `6.2.3` → `6.3.0`
- `react-native-gesture-handler`: `2.14.0` → `2.16.1`

Since `expo` includes specific versions of these packages with each release, manually changing the versions isn't feasible.

I recommend keeping this issue open until it is resolved and the package is compatible with the latest `expo` SDK 51.

**Comment by chen8520** [comment]
@Ucekay I performed the same operation, but there will be version compatibility issues
<img width="363" alt="image" src="https://github.com/PedroBern/react-native-collapsible-tab-view/assets/74804113/e7747a3e-4e94-472a-b325-a17bd069c88d">
<img width="371" alt="截屏2024-05-21 09 59 07" src="https://github.com/PedroBern/react-native-collapsible-tab-view/assets/74804113/c55a4342-be37-48bd-8267-80b828357f60">

**Comment by jayan2019** [comment]
> This package used to work seamlessly with `expo`. However, after upgrading from `expo` SDK 50 to SDK 51, the following dependencies were updated:
> 
> * `react-native-reanimated`: `~3.6.2` → `3.10.1`
> * `react-native-pager-view`: `6.2.3` → `6.3.0`
> * `react-native-gesture-handler`: `2.14.0` → `2.16.1`
> 
> Since `expo` includes specific versions of these packages with each release, manually changing the versions isn't feasible.
> 
> I recommend keeping this issue open until it is resolved and the package is compatible with the latest `expo` SDK 51 (`51.0.8` as of May 20th 2024).

In Android `Tabs.ScrollView` & `Tabs.FlatList` also not working

**Comment by jayan2019** [comment]
Based on this [3.13.0-rc.1](https://github.com/software-mansion/react-native-reanimated/issues/6066#issuecomment-2158235236) version of Reanimated working fine with all `Tabs.ScrollView `, `Tabs.FlatList` & `Tabs.MasonryFlashList` in both `iOS` & `Android`.

Currently my `package.json` is:
- `"expo": "^51.0.14",`
- `"react-native": "0.74.2",`
- `"react-native-reanimated": "~3.13.0-rc.1",`
- `"react-native-gesture-handler": "~2.16.1",`

**Comment by chen8520** [comment]
@jayan2019 "react-native-reanimated": "3.8.1"

**Comment by Ucekay** [comment]
> This package used to work seamlessly with `expo`. However, after upgrading from `expo` SDK 50 to SDK 51, the following dependencies were updated:
> 
> * `react-native-reanimated`: `~3.6.2` → `3.10.1`
> * `react-native-pager-view`: `6.2.3` → `6.3.0`
> * `react-native-gesture-handler`: `2.14.0` → `2.16.1`
> 
> Since `expo` includes specific versions of these packages with each release, manually changing the versions isn't feasible.
> 
> I recommend keeping this issue open until it is resolved and the package is compatible with the latest `expo` SDK 51 (`51.0.8` as of May 20th 2024).

I have created a patch for version 3.10.1 based on [the patch](https://github.com/software-mansion/react-native-reanimated/pull/5960#issuecomment-2098548412) for `react-native-reanimated` version 3.11.0. This will ensure that the header collapses correctly. However, I am not very familiar with this yet, so please use it at your own risk. (I am not sure if this will be a solution to Expo’s recommendation for specific package versions.)
[react-native-reanimated+3.10.1.patch](https://github.com/user-attachments/files/15898896/react-native-reanimated%2B3.10.1.patch)
