### ISSUE TITLE
New Architecture react-native-pager-view@6.3.4 incompatible (android only)

### ISSUE THREAD

**Issue by renyufei8023** [PedroBern/react-native-collapsible-tab-view#440]
react-native:0.74.5 newArchEnabled=true
react-native-collapsible-tab-view:6.2.1 | 8.0.0
react-native-pager-view:6.3.4

<Tab.FlatList/> no render

like this:
![Screenshot_20240821_104641_com changyou ecosteam](https://github.com/user-attachments/assets/bf3dedde-e5a1-4e45-8df1-8f9c8c9bdba4)

If this library is replaced with react-native-pager-view@6.2.3, it can be displayed normally

this is my code：
<img width="1105" alt="截屏2024-08-21 11 10 10" src="https://github.com/user-attachments/assets/75a84cb4-744f-4cfe-90ca-e098dada363e">
<img width="1147" alt="截屏2024-08-21 11 10 59" src="https://github.com/user-attachments/assets/3aa5373f-25cc-4ef3-a480-797fb1251af0">

**Comment by mozzius** [comment]
This patch fixes it

https://github.com/mozzius/graysky/blob/4435189b1e3a992133fed287bc46397992649153/patches/react-native-collapsible-tab-view.patch

**Comment by renyufei8023** [comment]
@mozzius Thank you for solving my problem

**Comment by frozencap** [comment]
why is this closed? issue isn't fixed in lib

**Comment by wardjk87** [comment]
this needs to be merged to be fixed
