### ISSUE TITLE
Jittery behaviour?

### ISSUE THREAD

**Issue by alexpchin** [PedroBern/react-native-collapsible-tab-view#59]
Hi @PedroBern, I've finally gotten around to have a look at the new v3 implementation. 

On running the example, I see: `You specified `onScroll` on a <ScrollView> but not `scrollEventThrottle`. You will only receive one event. Using `16` you get all the events but be aware that it may cause frame drops, use a bigger number if you don't need as much precision.`

I don't know if it's related yet, but I'm also seeing quite jittery behaviour. Please see video:

[simulator1.mov.zip](https://github.com/PedroBern/react-native-collapsible-tab-view/files/5893215/simulator1.mov.zip)

I haven't fully investigated this and will add more information if/when I find out more.

**Comment by PedroBern** [comment]
Hi @alexpchin thanks for running the example. Looks like it's iOS-specific. It's perfect on android here. Can you please do me a favor, experiment with `scrollEventThrottle` on the examples, and tell me the result. You can either add it directly in the `ScrollView` / `FlatList` on the examples folder or by adding a default value in the `src/createCollapsibleTabs`.

**Comment by alexpchin** [comment]
@PedroBern Will do! I haven't gotten the whole way through reading the updates yet! You've definitely been busy. I need to experiment with adding a different `TabBarComponent`.  The one I'm using has badge icons rather than labels and Dot indicators for new messages etc.

**Comment by PedroBern** [comment]
@alexpchin thanks! yes quite a work, but was fun! The default tab bar isn't documented yet, but it's easy to add a custom `TabItem`, and leverage the default indicator and scrollable tabs behavior, [here is an example](https://github.com/PedroBern/react-native-collapsible-tab-view/pull/58/commits/4db1b638295fc9148f276e26b424abb5b6681b33#diff-b2a4de61f1bfc596d553f0c11c6956e74357747f6e92f0982291e00e852d6a41R83) in the upcoming react-navigation integration.

**Comment by PedroBern** [comment]
@alexpchin I added `scrollEventThrottle={16}` on #60, not sure if it will fix this, but just because I was also doing other things

**Comment by alexpchin** [comment]
Just working through integrating into my project which does not use `expo`. Here are my WIP thoughts:

- [ ] Perhaps we should make it clearer that the project uses v2 of `react-native-reanimated`?
- [ ] On the first setup, I'm getting `Encountered two children with the same key, `undefined`.
- [ ] Currently with `snapEnabled` the content is not animating.
- [ ] You can't click on the tabs once you have started to scroll but have not scrolled the whole way up (Content is not snapping, so you can be mid-scroll).
- [ ] Even though you can't click on the tabs, you can swipe
- [ ] Unusual scenario, I know but, if you only have one key/value in `refMap`, I believe this would throw an error?
- [ ] How to navigate programmatically to a tab (previously used to be able to update the index of navigationState).

I am just going through everything at the moment...

**Comment by PedroBern** [comment]
> - [ ] Perhaps we should make it clearer that the project uses v2 of react-native-reanimated?
 
I will add it to the readme

> - [ ] On the first setup, I'm getting Encountered two children with the same key, undefined`.

Where? On the quick start code?

> - [ ] Currently with snapEnabled the content is not animating.
> - [ ] You can't click on the tabs once you have started to scroll but have not scrolled the whole way up (Content is not snapping, so you can be mid-scroll).
> - [ ]  Even though you can't click on the tabs, you can swipe

This is weird, here is all working 😕  Not sure if I understand it. As the snap works for me, I can't see this bug.

> - [ ] Unusual scenario, I know but, if you only have one key/value in refMap, I believe this would throw an error?

Good question, I didn't test it but should work

> - [x] How to navigate programmatically to a tab (previously used to be able to update the index of navigationState).

I added a ref in #58 to control the back behavior when navigating back. [See it here](https://github.com/PedroBern/react-native-collapsible-tab-view/pull/58/files?file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.tsx#diff-3906fff0657ff5cba0b9a377821c45c0a84757442f33687b196579188e6f3235R371). This ref can be used to programmatically navigate between tabs, like this:

```tsx
const ref = React.useRef<RefType>()

const goToTab = () => {
    ref.current?.setIndex(name)
}

<Tabs.Container ref={ref} {...} />
```

**Comment by alexpchin** [comment]
@PedroBern Interesting. Snap isn't working for me. 

Can you uninstall `expo-cli` and do a fresh install from main? On running the new version, I am seeing: 

```
Some of your project's dependencies are not compatible with currently installed expo package version:
 - react-native-gesture-handler - expected version range: ~1.8.0 - actual version installed: ^1.9.0
 - react-native-reanimated - expected version range: ~1.13.0 - actual version installed: 2.0.0-rc.0
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
```

I might be missing something really obvious... I've re-installed `expo-cli` and re-pulled main?

**Comment by PedroBern** [comment]
It's correct, I get the same warning, it's because SDK 40 is not supposed to use reanimated v2 (yet) but [expo says it's ok](https://docs.expo.io/versions/latest/sdk/reanimated/#experimental-support-for-v2)

I've just done a fresh install, everything is working, including the snap. Does the snap work on android for you?

**Comment by alexpchin** [comment]
@PedroBern I just ran the example on the Android emulator and can confirm that the snap does work. Does it work for you on iOS at your end?

**Comment by andreialecu** [comment]
I have left some related comments here: https://github.com/PedroBern/react-native-collapsible-tab-view/pull/58#issuecomment-770047353

Unfortunately there are a lot of problems on iOS with v3. Going to take a look at the implementation myself today.

**Comment by alexpchin** [comment]
Also, just another few thoughts:

- [ ] How to get the currently focused tab from refMap, previously you could use `navigationState.index`?
- [ ] How to listen to the change of the tab? (Connected to above)
- [ ] Is it possible to disable `swipeEnabled` ? 
- [ ] Currently, the refMap uses the keys to create the labels. If we changed the structure of refMap, it could take a `label` or component/icon it might allow for more customisation. 

```js
{
  screen1: { ref: ref, label: label },
  screen2: { ref: ref, label: label }
}
```

**Comment by andreialecu** [comment]
Here are some of the issues I found:

Scroll position doesn't seem to sync right when the header is partly visible:

https://user-images.githubusercontent.com/697707/106351679-26546f80-62e6-11eb-9f0e-6481dea6d6f4.MP4

Snap only works when momentum scrolling rests, but not if you lift the finger while scrolling (zip because it's over the 10 mb limit for videos):

[RPReplay_Final1611995394.MP4.zip](https://github.com/PedroBern/react-native-collapsible-tab-view/files/5897611/RPReplay_Final1611995394.MP4.zip)

Tapping the tab bar to switch tabs only works when first opening a screen, as soon as you scroll a bit, they don't respond any more:


https://user-images.githubusercontent.com/697707/106351773-ea6dda00-62e6-11eb-98ef-ee0adb36b55d.MP4

Elastic scrolling via momentum, or by overscrolling with the finger doesn't work. It just stops abruptly at either edge (example of what I mean here: https://medium.com/@wcandillon/ios-bounce-list-effect-with-react-native-5102e3a83999):


https://user-images.githubusercontent.com/697707/106351817-3caefb00-62e7-11eb-96dc-b4a88865b3d6.MP4

**Comment by andreialecu** [comment]
On iOS `onMomentumEnd` only triggers when scrolling eventually rests after a bigger swipe: 

https://github.com/PedroBern/react-native-collapsible-tab-view/blob/d9642e195d48ec5c253b57711eab8e7144c11dd2/src/createCollapsibleTabs.tsx#L529-L531

It doesn't trigger for touches that drag the view.

**Comment by alexpchin** [comment]
Side point, potentially, we should ensure that `children` exists here? 

```js
const scrollY = useSharedValue([...new Array(children.length)].map(() => 0));
```

**Comment by andreialecu** [comment]
It appears that most of the issues I mentioned above are related to the `onMomentumEnd` event.

The reason is that `isGliding.value = true` is being set in `onEndDrag`, but because momentum doesn't start, it's never reset. Thus breaking everything else.

One way to potentially solve it is to set `isGliding` to `true` on `onMomentumBegin`. Then start a timer in `onEndDrag`, and if `isGliding` wasn't set to true after a few frames (16, 32ms) then force the snap effect manually. There would need to be some debouncing going on as well, and seems finicky to get right. It was pretty much the same v2 was doing.

Also, the overscroll situation seems to be resolved if this is omitted or set to `true`:

https://github.com/PedroBern/react-native-collapsible-tab-view/blob/d9642e195d48ec5c253b57711eab8e7144c11dd2/src/createCollapsibleTabs.tsx#L650

Not yet sure why it was forced to `false`/

**Comment by andreialecu** [comment]
```diff
diff --git a/src/createCollapsibleTabs.tsx b/src/createCollapsibleTabs.tsx
index 08f97d8..8c1c560 100644
--- a/src/createCollapsibleTabs.tsx
+++ b/src/createCollapsibleTabs.tsx
@@ -15,6 +15,7 @@ import Animated, {
   scrollTo,
   withTiming,
   runOnJS,
+  runOnUI,
 } from 'react-native-reanimated'
 
 import MaterialTabBar, {
@@ -509,6 +510,56 @@ const createCollapsibleTabs = <
       tabNames.value.findIndex((n) => n === name)
     )
 
+    const onMomentumEnd = () => {
+      'worklet'
+      if (snapEnabled) {
+        if (diffClampEnabled && accDiffClamp.value > 0) {
+          if (scrollYCurrent.value > headerHeight) {
+            if (accDiffClamp.value <= headerHeight * snapThreshold) {
+              // snap down
+              isSnapping.value = true
+              accDiffClamp.value = withTiming(0, undefined, () => {
+                isSnapping.value = false
+              })
+            } else if (accDiffClamp.value < headerHeight) {
+              // snap up
+              isSnapping.value = true
+              accDiffClamp.value = withTiming(headerHeight, undefined, () => {
+                isSnapping.value = false
+              })
+            }
+          } else {
+            isSnapping.value = true
+            accDiffClamp.value = withTiming(0, undefined, () => {
+              isSnapping.value = false
+            })
+          }
+        } else {
+          if (scrollYCurrent.value <= headerHeight * snapThreshold) {
+            // snap down
+            snappingTo.value = 0
+            // @ts-ignore
+            scrollTo(refMap[name], 0, 0, true)
+          } else if (scrollYCurrent.value <= headerHeight) {
+            // snap up
+            snappingTo.value = headerHeight
+            // @ts-ignore
+            scrollTo(refMap[name], 0, headerHeight, true)
+          }
+          isSnapping.value = false
+        }
+      }
+      isGliding.value = false
+    }
+
+    const maybeGlide = () => {
+      setTimeout(() => {
+        if (isGliding.value !== true) {
+          runOnUI(onMomentumEnd)()
+        }
+      }, 50)
+    }
+
     const scrollHandler = useAnimatedScrollHandler(
       {
         onScroll: (event) => {
@@ -524,53 +575,13 @@ const createCollapsibleTabs = <
           isScrolling.value = true
         },
         onEndDrag: () => {
-          isGliding.value = true
           isScrolling.value = false
+          runOnJS(maybeGlide)()
         },
-        onMomentumEnd: () => {
-          if (snapEnabled) {
-            if (diffClampEnabled && accDiffClamp.value > 0) {
-              if (scrollYCurrent.value > headerHeight) {
-                if (accDiffClamp.value <= headerHeight * snapThreshold) {
-                  // snap down
-                  isSnapping.value = true
-                  accDiffClamp.value = withTiming(0, undefined, () => {
-                    isSnapping.value = false
-                  })
-                } else if (accDiffClamp.value < headerHeight) {
-                  // snap up
-                  isSnapping.value = true
-                  accDiffClamp.value = withTiming(
-                    headerHeight,
-                    undefined,
-                    () => {
-                      isSnapping.value = false
-                    }
-                  )
-                }
-              } else {
-                isSnapping.value = true
-                accDiffClamp.value = withTiming(0, undefined, () => {
-                  isSnapping.value = false
-                })
-              }
-            } else {
-              if (scrollYCurrent.value <= headerHeight * snapThreshold) {
-                // snap down
-                snappingTo.value = 0
-                // @ts-ignore
-                scrollTo(refMap[name], 0, 0, true)
-              } else if (scrollYCurrent.value <= headerHeight) {
-                // snap up
-                snappingTo.value = headerHeight
-                // @ts-ignore
-                scrollTo(refMap[name], 0, headerHeight, true)
-              }
-              isSnapping.value = false
-            }
-          }
-          isGliding.value = false
+        onMomentumBegin: () => {
+          isGliding.value = true
         },
+        onMomentumEnd,
       },
       [headerHeight, name, diffClampEnabled, snapEnabled]
     )
@@ -677,7 +688,7 @@ const createCollapsibleTabs = <
     return (
       <Animated.ScrollView
         ref={refMap[name] as any}
-        bounces={false}
+        //bounces={false}
         bouncesZoom={false}
         style={[_style, style]}
         contentContainerStyle={[
```

This diff seems to fix all of the issues I mentioned above, but it needs some cleanup for the `setTimeout` handling.

I notice that the `DiffClamp` example gets broken though, and keeps pushing the header up a bit every time. This is probably related to `bounces`. Here's a longer recording with these changes:

https://streamable.com/5a4aeo

**Comment by PedroBern** [comment]
Im not at home right now, when I get there I will iterate over all comments. Just one thought, I saw some issues on reaninated, related to scroll on iOS that were fixed in rc.1 and rc.2, but the example folder is using rc.0

**Comment by andreialecu** [comment]
I opened #65 which fixes all of the issues I reported from my initial testing.

@alexpchin if you could test it as well it would be great. I'm not sure about the jittery behaviour, seems to work fine on my physical device (iPhone 12 Pro Max).

**Comment by andreialecu** [comment]
Oh, and good job @PedroBern on the rewrite 🏆 . The implementation looks much better now with Reanimated.

**Comment by PedroBern** [comment]
> Oh, and good job @PedroBern on the rewrite 🏆 . The implementation looks much better now with Reanimated.

@andreialecu thanks man 👍 

>Also, just another few thoughts:

> How to get the currently focused tab from refMap, previously you could use navigationState.index?
 How to listen to the change of the tab? (Connected to above)
 Is it possible to disable swipeEnabled ?
 Currently, the refMap uses the keys to create the labels. If we changed the structure of refMap, it could take a label or component/icon it might allow for more customisation.
{
  screen1: { ref: ref, label: label },
  screen2: { ref: ref, label: label }
}

@alexpchin better to open a new issue so we can discuss it without noise... But you can disable swiping with `pagerProps={{scrollEnabled: false}}`.

**Comment by alexpchin** [comment]
@PedroBern @andreialecu I've gone through and moved unrelated comments to their own issues and updated my comments to reduce noise and make them easier to fix. I will now start looking at them.
