### ISSUE TITLE
How to get current tab from outside the TabContext?

### ISSUE THREAD

**Issue by alexpchin** [PedroBern/react-native-collapsible-tab-view#71]
- [ ] How to get the currently focused tab from refMap, previously you could use `navigationState.index`?
- [ ] How to listen to the change of the tab? (Connected to above)

If you want to conditionally display content based on the current tab, or you just want to know for some logic which tab is currently focused, you used to be able to work this out from `navigationState`.

**Comment by PedroBern** [comment]
> How to get the currently focused tab from refMap, previously you could use navigationState.index?
> How to listen to the change of the tab? (Connected to above)

#58 will add `onIndexChange` prop, [here](https://github.com/PedroBern/react-native-collapsible-tab-view/blob/feat-react-navigation/src/createCollapsibleTabs.tsx#L69), and the imperative ref handler [here](https://github.com/PedroBern/react-native-collapsible-tab-view/blob/feat-react-navigation/src/createCollapsibleTabs.tsx#L379), maybe we can add more methods to it, like `currectTab: () => focusedTab .value` and `currentIndex: () => index.value`
