### ISSUE TITLE
CenteredEmptyList Example is Commented out

### ISSUE THREAD

**Issue by alexpchin** [PedroBern/react-native-collapsible-tab-view#78]
Currently, the CenteredEmptyList example differs from the v2 example, as it doesn't take value for the current tab/index. 
How come this was commented out? What issue was being faced?

<img width="462" alt="Screenshot 2021-01-31 at 11 58 40" src="https://user-images.githubusercontent.com/40461/106383082-b0223c80-63bb-11eb-953f-eabeca3bef9f.png">

**Comment by PedroBern** [comment]
It's not syncing correctly. We will probably need to add something like `visibleHeader` to the context, so we can interpolate with the current visible header height.

**Comment by PedroBern** [comment]
Actually, we just need to get the translateY value from the header. I will add this during the week, today I'm away.

**Comment by alexpchin** [comment]
My version is actually working now.  #80
