### ISSUE TITLE
TabBar Item Label style required

### ISSUE THREAD

**Issue by sanbat** [PedroBern/react-native-collapsible-tab-view#82]
### Feature request
Please provide an option for changing the Tab Bar Item Label Style. 
In #64, you provided an option for changing the tab bar background, that is great. 

But need an option to change the existing label style without using custom 'TabItemComponent' as you mentioned in #70.

Waiting for your valuable reply.

**Comment by tcorreiaubi** [comment]
Hey @sanbat can you test #83 and see if it fits all your needs?

**Comment by PedroBern** [comment]
@sanbat the only way at the moment is:

```tsx
TabItemComponent={(props) => <MaterilaTabItem {...props} labelStyle={myStyle} />}
```

**Comment by sanbat** [comment]
@PedroBern Not working...

**Comment by sanbat** [comment]
@tcorreiaubi yes #83 is working(5eb7708)

I think it should be merged to this package. Thank you.
