### ISSUE TITLE
Using `snapToOffsets` instead of the custom snap code

### ISSUE THREAD

**Issue by andreialecu** [PedroBern/react-native-collapsible-tab-view#9]
I noticed that there's some sort of loop happening when doing very small momentum scrolls within the header. 

I'm not sure if this reproduces outside of my project, and I also use `react-navigation` via a WIP PR I'm working on for #7

What seems to be happening is that `onMomentumScrollEnd` triggers via the user gesture, then `syncScrollOffset` calls `scrollScene` which then also triggers `onMomentumScrollEnd` and then there's a battle between the two triggering a loop.

This seems to have also been reported here: https://stackoverflow.com/questions/61715531/abrupt-scrolltooffset-calls-in-onmomentumscrollend-react-native

However, it seems to be possible to use https://reactnative.dev/docs/scrollview#snaptooffsets with values of `[0, headerHeight]` to achieve the same behavior as the custom scroll snapping. Is there any reason not to use `snapToOffsets`?

A current workaround is to set `disableSnap` to true and add `snapToOffsets` to my own list views

**Comment by andreialecu** [comment]
I guess one reason for using the custom snap code is the ability to override the `snapThreshold`. 

The native `snapToOffsets` prop has improved behavior and stops momentum scrolling at the snap points, so the header doesn't peek through before snapping back, which may be preferable.

**Comment by andreialecu** [comment]
May need to verify that it doesn't break cases when the tab content slightly overshoots the window size by less than the snap offset, so it doesn't get stuck offscreen with the list snapping back and not allowing access to it.

**Comment by PedroBern** [comment]
The `snapToOffsets` and `snapToInterval` indeed are a better solution for the `ScrollView`, but won't work for the `FlatList`. The current implementation is a simple way to handle both cases at the same time/same way.

**Comment by PedroBern** [comment]
I did a quick test on the examples folder, adding `snapToOffsets={[0, HEADER_HEIGHT]}` to all scrollable components and running on the `Collapsible Tab View no snap` demo, wich has `disableSnap={true}`, and it looks like working fine for scroll view, but does not work for flatlist.

**Comment by andreialecu** [comment]
Weird. It works with FlatList in the app I'm working on with no issues. I didn't test the examples folder though, something must be different.

**Comment by andreialecu** [comment]
@PedroBern make sure to also add `snapToEnd={false}` otherwise the snap points keep repeating for the rest of the list, resulting in weird scrolling behavior.

**Comment by PedroBern** [comment]
> @PedroBern make sure to also add snapToEnd={false} otherwise the snap points keep repeating for the rest of the list, resulting in weird scrolling behavior.

😝  forgot, I will try it again later

**Comment by PedroBern** [comment]
@andreialecu Can you make a review of #11, please? There was one thing I didn't understand, after fixing #8 and moving to `snapToOffsets` if I didn't add [this line](https://github.com/PedroBern/react-native-collapsible-tab-view/blob/perf-snap/example/src/Shared/Albums.tsx#L56), the albums tab would double in height.

**Comment by andreialecu** [comment]
I was able to fix the glitch in #12. I propose we keep the custom snapping code and if someone wants to override they can use `disableSnap: true` and their own custom snap offsets.
