### ISSUE TITLE
Children Flatlist with horizontal direction not working

### ISSUE THREAD

**Issue by tcorreiaubi** [PedroBern/react-native-collapsible-tab-view#92]
### Current behavior

Configuring a flatlist with horizontal direction on a Tab.ScrollView is not working as expected, the content is being displayed vertically instead of horizontally

### Expected behaviour

The Content to be displayed in the horizontal direction

### Code sample

https://github.com/tcorreiaubi/CollapsibleTabViewsDemo

**Comment by tcorreiaubi** [comment]
@PedroBern Hey, sorry to bother, im a bit stuck on this one, not sure if this is caused because of the tabs being wrapped on a flatlist with horizontal direction

**Comment by PedroBern** [comment]
No worries :)

Yes maybe, I'm not sure, didn't have the time to test. Try to add nestedScrollEnabled={true}

**Comment by tcorreiaubi** [comment]
Just tested it, not working, I think the issue is related to the width that's forced to the ScrollView,
```typescript
  function useCollapsibleStyle(): CollapsibleStyle {
    const { headerHeight, tabBarHeight, containerHeight } = useTabsContext()
    const windowWidth = useWindowDimensions().width

    return {
      style: { width: windowWidth }, // If I remove the width the scroll does work, but obviously everything else stops working properly 
      contentContainerStyle: {
        minHeight: (containerHeight || 0) + headerHeight,
        paddingTop: headerHeight + tabBarHeight,
      },
      progressViewOffset: headerHeight + tabBarHeight,
    }
  }
 
```

```tsx
    const {
      style: _style,
      contentContainerStyle: _contentContainerStyle,
    } = useCollapsibleStyle()

    return (
      <Animated.ScrollView
        ref={refMap[name] as any}
        nestedScrollEnabled
        bouncesZoom={false}
        style={[_style, style]}
        contentContainerStyle={[
          _contentContainerStyle,
          // @ts-ignore
          contentContainerStyle,
        ]}
        onScroll={scrollHandler}
        scrollEventThrottle={16}
        {...rest}
      >
        {children}
      </Animated.ScrollView>
    )
  }
```

**Comment by tcorreiaubi** [comment]
Didn't work, strange enough, if I use a scrollview instead of a flatlist as child the content is displayed correctly, im confused

**Comment by tcorreiaubi** [comment]
I was able to get it working by disabling the scroll on the pagerProps and rendering a Tabs.Flatlist instead of scrollview and also passing the content as the prop ListEmptyComponent, feels kinda hacky, but I believe the issue is related with nesting a flatlist in the same direction, Tabs.container(aka horizontal flatlist) > Tabs.ScrollView/Tabs.Flatlist(vertical) > View > Flatlist horizontal
There was also some scenarios where I would lose the ref of nested flatlists

Just leaving the issue open to hear what you think about it, but feel free to close it if there's nothing to be added

**Comment by andreialecu** [comment]
See #163 for the same issue and a workaround.

**Comment by habovh** [comment]
@andreialecu same issue yes but a workaround is no fix. In my opinion one of these issues should remain open and deserves more attention.
