### ISSUE TITLE
Leaving some of the header at the top

### ISSUE THREAD

**Issue by danielfein** [PedroBern/react-native-collapsible-tab-view#95]
Well, last question for today, is there any way to have some sort of header when the tab bar gets sticky? So if on scroll the header disappears and the title of the page is now out of sight, is there any place for some replacement title/part of the header to exist?

I can't figure out where it would go given the header is included in the component itself. This isn't a problem in the Example gifs where the title is just in the nav bar, but that's not always the case.

Any thoughts on this one?

**Comment by tcorreiaubi** [comment]
I believe #85 covers your needs @danielfein
