### ISSUE TITLE
Support for Sectionlist

### ISSUE THREAD

**Issue by alexco2** [PedroBern/react-native-collapsible-tab-view#97]
Hello, first of all, amazing package. This is something the rn community definetly needs! One question though. Do you plan to support Sectionlist, or is there a way to make it work with sectionlist?

**Comment by andreialecu** [comment]
The refactoring made as part of #93 should make this very easy to add.

**Comment by andreialecu** [comment]
This will actually not be easily possible to do on iOS because of issues described in this comment: https://github.com/PedroBern/react-native-collapsible-tab-view/issues/136#issuecomment-780606731

**Comment by RoscoeZhao** [comment]
Hi @andreialecu , firstly I want to say thank you for this great component!
The PR which fixs the iOS offset issue, https://github.com/facebook/react-native/pull/30737 , has been merged to RN. Would you please add support for SectionList ? Thank you very much!

**Comment by andreialecu** [comment]
@RoscoeZhao unfortunately even though the PR was merged, RN0.64 does not include it.

You can verify by comparing https://cdn.jsdelivr.net/npm/react-native@0.64.0/React/Views/RefreshControl/RCTRefreshControl.m with the changes in the PR.

The release workflow of RN diverges from what is in master. Instead, they cherry pick commits:
https://github.com/react-native-community/releases/issues/221

RN 0.64.1 is not scheduled to have it either, as per the thread linked above.

**Comment by alexco2** [comment]
I asked for a cherrypick. If you give the comment some attention, perhaps I'll work ;)

**Comment by davidbiedenbach** [comment]
I guess 30737 finally made it into 0.65 =)

**Comment by alexco2** [comment]
@andreialecu since the PR is now included in RN 0.65, is there a plan to support sectionlist as well? :)

**Comment by andreialecu** [comment]
Sure, we can consider a PR that adds section list support if anyone is willing to implement it. 🙂

**Comment by alexco2** [comment]
Are there some considerations that come into your mind regarding the implementation of SectionList?

**Comment by alexco2** [comment]
@andreialecu I forked this repo and made sectionlist work. I will test it further and commit a PR if everything works fine. Also, I will look into bumping reanimated to version 2.2.2. https://github.com/PedroBern/react-native-collapsible-tab-view/issues/164

**Comment by alexco2** [comment]
I commited the PR. Please let me know if anything is missing. Would be happy if the feature could be merged and shipped :)
https://github.com/PedroBern/react-native-collapsible-tab-view/pull/201
